compucorp/uk.co.compucorp.membershipextras

CRM/Membership/Upgrader.php
CRM/Membership/Utils/Contribution.php
Drupal/compucorp_civicrm_membership/compucorp_civicrm_membership.info
Drupal/compucorp_civicrm_membership/compucorp_civicrm_membership.module
info.xml

Many changes are done here : 
1- I created a new drupal module inside this extension called **compucorp_civicrm_membership**, this module only implements the hook created here : https://github.com/compucorp/webform_civicrm-1/pull/3 for now to allow using any payment processors of type "**Offline_Recurring_Contribution**" to be used as a paylater payment processors in the webforms.
2- I followed up with kacper work and changed **isOfflineRecurring** method to use the defined payment processor instead of NULL.
3- I also added code to handle uninstalling/disabling and enabling the extension where to remove/disable/enable the defined payment processor and the defined payment processor type.

BASW-42: Several adjustments

---

CRM/MembershipExtras/Hook/Alter/CalculatedMembershipStatus.php
CRM/MembershipExtras/Hook/BuildForm/MembershipStatus.php
membershipextras.php

To manage membership status for those payed with a payment plan in several instalments, we need two events that will allow to check for when programmed payments are overdue:
- In arrears: triggered when a membership is paid by recurring contribution with instalments and at least one pending instalment contribution's receive date falls to the past.
- Not in arrears: no pending instalment contribution in the past.
There was no way to manage the status of a membership payed with instalments in regard to the status of those payments.
The two new events (In Arrears, Not In Arrears) were added as options to membership status form edit view, on **Start Event** and **End Event** fields.
Hook alterCalculatedMembershipStatus was implemented to go through the list of status rules sorted by weight, …

BASW-65: Add In Arrears Events to Membership Status Rules

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Upgrader.php
api/v3/OfflineAutoRenewalJob.php

A scheduled job  called“Renew offline auto-renewal memberships” is added.
When the scheduled job run, it finds and processes any membership that meets all following conditions:
1. Its last recurring contribution is using offline payment processor
2. Its last recurring contribution is set to auto-renew
3. Its last recurring contribution is not cancelled or refunded.
4. The membership's end date is equals to or smaller than today.
- If the membership's last recurring contribution has no installments (installments = NULL) then it will  generate a new pending contribution under that recurring contribution. Then it will extend the membership for one term.
- If the membership's last recurring contribution has installments (installments != NULL), the recurring contribution will be used as a …

BASW-68: Adding scheduled job to renew offline auto renewal memberships

---

CRM/MembershipExtras/Form/PaymentPlanSettings.php
CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/PaymentProcessor/OfflineRecurringContribution.php
membershipextras.php
settings/PaymentPlan.setting.php
sql/auto_uninstall.sql
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.tpl
xml/Menu/membershipextras.xml

When the "**offline memberships auto-renewal scheduled job**" runs, it will use the same price used in the last  payment, but sometimes and for some organizations, the membership price change and using the old price is no longer applicable.
In this PR we add a new configuration page called "**Payment Plan Configuration**" which can be accessed from the administer menu (or **civicrm/admin/payment_plan_settings**) that allow the user to toggle a checkbox called "**Use latest price when auto renew membership?**".
If the checkbox mentioned above is enabled, then the scheduled job will use the membership latest price when doing an auto-renew, if it is disabled then it will use the old price.

BASW-81: Add option for using last membership price when renewing offline memberships

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php
xml/customFields_install.xml

In the previous PR https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/11 we added the ability to configure the site to either to use the membership last price or its previous price for offline membership auto-renewal scheduled job.
In this PR, we add a new custom group called "**Offline auto-renew option**" that contain a single Boolean custom field "**Opt-out auto price update for offline auto-renew**" for membership entity.
If this Boolean field is enabled for a specific membership, then it will not be affected whither "**Use latest price when auto renew membership?**"  is enabled or not, which means that the membership when get auto-renewed  will always use the previous price if this field is enabled.
In other words, it is a way to override **Opt-out auto price update …

BASW-82: Adding Optout from using last membership price option

---

CRM/MembershipExtras/Hook/Alter/CalculatedMembershipStatus.php

Calculation of arrears related statuses was failing.
We were checking for the membership's ID using CaculatedMembershipStatus class $membership attribute, but since that attribute wasn't set by the time the check was made, no memberships were being processed.
Fixed by doing the check after the class' attribute is set.

BASW-65: Fix Bug on Membership Status Alter Hook

---

CRM/MembershipExtras/Hook/PreEdit/Membership.php
CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Service/ManualPaymentProcessors.php

We where using 'Offline Recurring Contribution' payment processor for the scheduled job code to identify offline payment plan payments as well as in some other places, but we should use any payment processor with class name = 'Payment_Manual' instead which I fixed in this PR.

BASW-68: Ensure that Payment_Manual payment processors are used instaed of offline recurring contribution processor

---

CRM/MembershipExtras/Hook/PreEdit/Membership.php
CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Service/MembershipEndDateCalculator.php
membershipextras.php

When renewing a membership using "payment plan" option and selecting the payment status as "pending", the line item amounts will not be correct and the membership will not get extended.
The membership extending part is how civicrm core work, it does not extend the membership unless u complete the related membership payment but still for this extension we should extend it when paying via payment plan. The extending should be similar to how it work in offline renewal scheduled job.
Now the line items amounts are correct and the membership get extended as soon as u submit the renewal form.
- The logic that calculates the end date for extending the membership is moved to a new class called : **CRM_MembershipExtras_Service_MembershipEndDateCalculator** , this class is now used in hooks when …

BASW-90: Fixing line item amounts and membership end date when renewing memberships

---

CRM/MembershipExtras/Form/CancelRecurringContribution.php
CRM/MembershipExtras/Hook/Links/RecurringContribution.php
membershipextras.php
templates/CRM/MembershipExtras/Form/CancelRecurringContribution.tpl
xml/Menu/membershipextras.xml

When cancelling a recurring contribution, a popup will show up and ask for confirmation. A new dialog box containing two checkbox options should be used to replace the popup.
The first checkbox is "Do you wish to cancel any pending instalment contribution?" which if checked and confirmed, as a result, all "Pending" contributions that are linked to the recurring contribution will also be cancelled.
The second checkbox is "Do you wish to cancel any linked membership?" which if checked and confirmed, as a result, all memberships that are linked to the recurring contribution will also be cancelled.
Enable/Disable CiviCRM Page was being used to handle recurring contribution cancellation.
Altered the cancellation link on recurring contributions list so it uses a new form, with the required …

BASW-113: Cancel Existing Payment Plan

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/PaymentProcessor/OfflineRecurringContribution.php
CRM/MembershipExtras/SettingsManager.php
settings/PaymentPlan.setting.php
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.hlp

A new option called "Days to renew in advance" with help text "Number of days in advance of membership end date should an offline auto-renew membership get renewed." should be added to  "payment plan settings" Form.
If this field is not 0 or NULL, the "renew offline membership" scheduled job should renew memberships for a number of days specified in this setting in advance of its end date.
Here is the new setting in settings page : 
And here is an example of it : 
In the example above, (Today Date = 17-5-2018) where (Membership End Date = 20-5-2018), and ("Days to renew in advance" = 2) so running the auto-renewal scheduled job does not auto-renew the membership since (20-5-2018 minus two days = 18-5-2018). But when I changed the ("Days to renew in advance" ) to 3, (20-5-2018 minus three …

BASW-92: Adding (Days to renew in advance) setting

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php

In DD-29, direct deb extension need to create some CiviCRM Activities after the auto-renewal job renew a membership.
A new hook is created inside this extension which is called directly after the offline auto-renewal job extend a membership for renewal.
The new Hook name and signature is  : 
**hook_membershipextras_postOfflineAutoRenewal($membershipId, $recurContributionId)**
which means that it will pass both the auto-renewed membership ID as well as its current recurring contribution ID that is used for renewal.
The hook can be implemented inside an CiviCRM extension as following : 
```php
function myextensionname_membershipextras_postOfflineAutoRenewal($membershipId, $recurContributionId) {
// Do your stuff here
}
```

DD-29: Adding post hook for membership offline auto-renewal job

---

CRM/MembershipExtras/Upgrader.php
sql/auto_uninstall.sql
sql/set_unique_external_ids.sql
xml/customFields_install.xml

This implements both parts of the ticket:
1) creating custom fields to support External ID for all 4 entities. Custom fields definitions for Contribution, Recurring Contribution, Memberships are added to customField xml file ,  but for Line Item is done via API
2) Additional requirements - adding unique constraint for  external ids  on install() and removing fields when extensions is uninstalled 
---
some notes:
- External ID custom fields were supposed to be inactive so both custom group and custom field have property is_active=0. Please advise if it is correct
- Line Item is added as option value to cg_extends_object, but not removed when extension is uninstalled.

DD-26: Create External ID for Direct Debit Related Entities

---

CRM/MembershipExtras/Hook/BuildForm/MembershipOfflineAutoRenew.php
CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
CRM/MembershipExtras/Service/InstallmentReceiveDateCalculator.php
membershipextras.php
templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl

We need to alter Update Recurring contribution form to expose some new fields and allow users to update related pending installments if they choose to do so. For this, we need to:
- Make "Number of instalment" field readonly if the recurring contribution is using a payment processor with "Payment_Manual" class.
- Expose the "Auto Renew?" field on "Update Recurring Contribution" form.
- Expose "Payment Method" field, "Cycle Day" field on "Update Recurring Contribution" form.
- When admin click on save on "Update Recurring Contribution" form, if "Payment Mehod" or "Cycle Day" is changed, a popup should appear asking "Do you want to update any outstanding instalment contribution with the new Payment Method/ Cycle Day?".
- If admin chose "No" in the previous popup. No existing contribution …

BASW-118: Update Installments on Recurring Contribution Update

---

CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlan.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

Validation message for installments details fields goes outside the frame, of the modal dialog to create memberships.
Validation Messages for installment quantity and frequency were breaking styling of the form. Also, when validation failed, the form was being shown again, but as if a single contribution was used, instead of a payment plan.
Altered template to remove messages that were causing break and added logic so if validation fails, the state of the form is preserved according to what payment option was chosen, contribution or payment plan.

BASW-90: Fix Styling and Usability Problems

---

CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlan.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

When creating a membership, if the default installment options are unchanged, the amount for the first invoice will not be calculated, and remain empty. Also, the payment toggler stopped working.
Payment toggle stopped working and ceased to show installments options. If the default installment options are unchanged, the amount for the first invoice was not be calculated.
Fixed both problems by fixing id used in selector to obtain DOM node and precalculating invoice amount by simulating a change event on number of installments.

BASW-141: Fix Problems With Payment Toggler

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php
membershipextras.php

It appear that I mistakenly changed the class name before committing it from CRM_MembershipExtras_Hook_Post_EntityFinancialTrxn to CRM_MembershipExtras_Hook_Pre_EntityFinancialTrxn so in this PR I changed it back.
I also changed the payment plan status update code so it is "In Progress" whenever the number of partially or paid payments is >= 1 . the "Completed" statues will still override it if the total number of paid installments >= the payment plan installments number.

BASW-122: Fixing issues with payment plan status update

---

CRM/MembershipExtras/Service/MembershipInstallmentsHandler.php

If the contribution passed tax amount was sent as string such as "0.00", then this if statment
```php
if (!empty($contribution->tax_amount)) {
CRM_Financial_BAO_FinancialItem::add($newLineItem, $contribution, TRUE);	
}
```
will get computed to true since the passed string is no empty though the tax amount is 0 which causing problems.
In this PR I convert the type to float to ensure that the validation is correct and no financial item will be created if the tax amount is 0.

BASW-90: Fixing tax amount validation

---

CRM/MembershipExtras/Hook/Links/RecurringContribution.php
CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
membershipextras.php

If a recurring contribution is set to auto-renew, then it will become uneditable. We need to change this to allow any auto-renew recurring contribution who are using offline payment processors (payment manual class) to be editable. 
On the other hand, when a recurring contribution that links to a membership is set to auto-renew, the id of the recurring contribution should also be filled into the membership contrib_recurr_id column.
Finally, after editing and saving the Cycle Day, the pending contributions Received date will change. However, opening the recurring contribution view modal will still show the old date. Also, when you uncheck the Auto Renew field and save, the changes do not reflect.
- All recurring contributions set to auto-renew were uneditable.
- Setting recurring …

BASW-118: Fix Issues on Recurring Contribution Update

---

CRM/MembershipExtras/Form/PaymentPlanSettings.php
CRM/MembershipExtras/Service/ManualPaymentProcessors.php

Manually adding a new payment processor creates two different items, with the same name, one with is_test = 0, the other one with is_test = 1. This made it impossible to know which was which on the extension's settings form, where we were just showing the processor's name.
Settings page for the extension only showed processor's name on the selection bx used to define default payment processor.
Added 'Live - ' and 'Test - ' prefixes correspondingly to each processor, so users can know which is which.

BASW-91: Show if Payment Processors are Live or Not on Settings

---

membershipextras.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

We want to allow the staff to edit the amount for a payment plan when the following criteria are met:
1. the staff is creating new membership using payment plan or renewing a membership using payment plan
2. priceset option is not used
The final value in the amount field will be the amount for the payment plan. It will be divided by the number of instalments and then used as the instalment contribution amount and the line amount.
Total amount field was being made read-only if payment plan was used to paid for a membership.
Total amount field is set to readonly if priceset is used to pay for the membership exclusively.
Also fixed a problem with updating amount of first invoice when using price set.

BASW-175: Unlock the Amount Field for Payment Plan when no Priceset is Used

---

CRM/MembershipExtras/Form/CancelRecurringContribution.php

If Membership is Cancelled when cancelling a recurring contribution, we need to make sure the 'status_override_end_date' field is set to null. This is not happening.
Updating the membership's status to 'Cancelled' when canceling a recurring contribution was setting it as an overridden status, but did not take into account the membership could already be in an overridden status until a specified date. This caused the membership to exit the cancelled status on the date specified for the previous status.
Set the `status_override_end_date` field to null whan cancelling the membership.

BASW-113: Set 'Override Until' Date to Null when Cancelling Recurring Contribution and Membership

---

CRM/MembershipExtras/Form/PaymentPlanSettings.php
CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Service/CustomFieldsCopier.php
CRM/MembershipExtras/Service/MembershipInstallmentsHandler.php
CRM/MembershipExtras/SettingsManager.php
settings/PaymentPlan.setting.php
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.hlp

When the the offline auto-renewal scheduled job auto-renew the offline memberships, the new contributions and the new recurring contribution will not have the custom fields exsisted in the previous contributions and recurring contribution, but we need all of them to be copied, we also want a setting that prevent certain custom groups fields to be copied such as odoo sync information custom group.
The offline auto-renewal scheduled job now copy all the contributions and recurring contribution custom fields from the previous ones. it also has a new multi-select box setting that allow users to choose which custom groups to exclude during the copy.
I also changed the signature of : 
membershipextras_postOfflineAutoRenewal
hook to pass the previous recurring contribution ID (the recurring …

BASW-211: Copy custom groups during offline auto-renew and add settin to allow for exculding some custom groups

---

CRM/MembershipExtras/Hook/Links/RecurringContribution.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl
xml/Menu/membershipextras.xml

We need to add a "View/Modify Future Instalments" action to any recurring contribution that uses an offline payment processor (payment processor with payment manual class).
When the action is selected, a "Manage Instalments" modal popup should appear.
In the current period tab (default), each "offline_contribution_recur_line_item" with empty end date should be displayed. Each row should have the following information:
- Item - line item label
- Start date - start_date in offline_contribution_recur_line_item
- End date - biggest end date among all linked memberships
- Renew automatically - auto_renew in offline_contribution_recur_line_item. This should not show if the recurring contribution is not auto-renew.
- Financial type - financial type of the line item
- Tax - the tax percentage of …

BASW-212: View a Recurring Contribution's Line Items

---

CRM/MembershipExtras/Form/PaymentPlanSettings.php
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.hlp

This PR : 
1- Ensure that only active custom groups appear on the "custom fields to exclude" setting field.
2- Improve the help text for the same field

BASW-211: Fixes and improvements to "custom fields to exclude" setting field

---

CRM/MembershipExtras/Hook/Alter/CalculatedMembershipStatus.php

Cancelled payment plan should not be counted when considering either trigger.
If a contact has a membership that starts at 01/01/2017 and ends at 31/12/2019
a) If the membership links to two payment plans:
1. payment plan in 12 instalments, starts 01/01/2017 ends 31/12/2018, status in progress, a pending instalment in the past
1. payment plan in 12 instalments, starts 01/08/2018 ends 31/7/2019, status pending, 12 pending instalments in the future
The membership should be in arrears.
b) If the membership links to two payment plans:
1. payment plan in 12 instalments, starts 01/01/2017 ends 31/12/2018, status cancelled, a pending instalment in the past
1. payment plan in 12 instalments, starts 01/08/2018 ends 31/7/2019, status pending, 12 pending instalments in the future
The membership …

BASW-65: Ensure the any cancelled payment plan will not be counted in arrears

---

xml/customFields_install.xml

The label "title of "Offline auto-renew option" custom group is changed to "Offline auto-renew pricing"

BASW-82: Change 'Offline auto-renew option' custom group label to 'Offline auto-renew pricing'

---

xml/Menu/membershipextras.xml

Permission to cancel a payment plan’s recurring contribution was 'administer CiviCRM'. We need to change this so users with edit contributions AND edit memberships permissions.
Permission set on route in Menu XML was administer CiviCRM.
Permission to cancel recurring contributions was changed from administer CiviCRM to require both edit contributions AND edit memberships permissions.

BASW-113: Fix Permissions for Payment Plan Cancellation

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

In the "Manage Installments" modal popup, we need to add a next period tab that should be shown if the recurring contribution has auto-renew enabled and it has at least one membership.
In the next period tab (default), each "offline_contribution_recur_line_item" with auto-renew = TRUE should be displayed. Each row should have the following information:
- Item - line item label
- Financial type - financial type of the line item
- Tax - the tax percentage of the financial type, show N/A if there is no tax account in the financial type
- Amount - line total of the line item
- Remove button - show as bin icon
- An "Add Membership" button and an "Add Other Amount" button should be shown under the last row
At the bottom of the tab, the following information should be shown:
- Untaxed Amount - …

BASW-217: View a Recurring Contribution's Next Period Line Items

---

CRM/MembershipExtras/Form/RecurringContribution/RemoveLineItems.php
CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
CRM/MembershipExtras/Service/FinancialTransactionManager.php
templates/CRM/MembershipExtras/Form/RecurringContribution/RemoveLineItems.tpl
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl
xml/Menu/membershipextras.xml

As part of the management of line items associated to a payment plan (recurring contribution), we need to add a way to remove those line items and have that affect any payments that are still pending for the payment plan. To do this, the trash -bin icon on the line item list for the recurring contribution should be used to implement the removal.
1. Once the bin button is clicked, if the item is the last item in the current period tab, a notice with warning sign should appear with text "Cannot remove the last item in an order" and action should be cancelled.
2. Once the bin button is clicked, if the item is not the last item in the current period tab, a dialog with title "Remove LINE_ITEM_LABEL ?" should appear with the following components:
- Dialog body text: "LINE_ITEM_LABEL amount …

BASW-218: Remove Payment Plan Line Items

---

templates/CRM/Member/Form/PaymentPlanToggler.tpl
templates/CRM/MembershipExtras/Form/CancelRecurringContribution.tpl
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.tpl

PR contains HTML fixes for Membership extras form so that they follow the default form markup of civicrm.
* Payment Plan Settings form 1
* Payment Plan Settings form 2
* Payment Plan Settings form 1
* Payment Plan Settings form 2
* Payment Plan Settings form 1
* Payment Plan Settings form 2
* Payment Plan Settings form 1
* Payment Plan Settings form 2
* Alignment fix for *Contribution and Payment Plan* toggle button box.
After alignment markup fixes. The alignment looks perfect with default Civi but looks a bit misaligned from left by 20px. To have this working with shoreditch we will need a new PR to the shoreditch theme as this will be a shoreditch specific fix. Please refer SHOR-50 (https://compucorp.atlassian.net/browse/SHOR-50)

SHOR-45: Fix Markup of forms to use default civi markup

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

To manage recurring pledges, we need to implement the following:
1. In the "View/Modify Future Instalments" next period tab, user can click on the bin button on each of the line item to perform a removal action.
2. Once the bin button is clicked, a dialog with title "Remove LINE_ITEM_LABEL?" should appear with the following components:
- dialog body text - "Please note the changes should take effect immediately after "Apply"."
- Cancel button
- Apply button
3. If user clicked on "Apply":
- auto_renew in offline_contribution_recur_line_item for the corresponding item should set to False.
- if the line item is a membership, clear the contribution_recurr_id of the corresponding membership (linked to the recurring contribution)
- a notice should appear with text "LINE_ITEM_LABEL should no …

BASW-219: Remove Line From Multi Line Membership Order

---

templates/CRM/Member/Form/PaymentPlanToggler.tpl

The membership renewal form is broken, it looks like this currently : 
The templates/CRM/Member/Form/PaymentPlanToggler.tpl file was parsing the tax rates JSON using JSON.pare(membershipextras_taxRatesStr), but if there are no tax accounts configured then the membershipextras_taxRatesStr will be empty and a JS error will be thrown that break the form. I added a check to ensure that the tax rates are not empty before parsing them.

DD-50: Fix membership renewal broken form

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

As per the ticket (BASW-223) overview, after modal pop reloads when a new other amount is added, it should automatically switch to the next period tab
After modal popup reloads, it does not automatically switch to the next period tab.
Modal popup switches to next period tab when other amount is added

BASW-223: Fix Modal Reload Auto Switch To Next Period Tab

---

CRM/MembershipExtras/PaymentProcessor/OfflineRecurringContribution.php

If the site does not have a financial account  type called '**Deposit Bank Account**' then it will cause problems during the extension installation.
I removed the financial account type parameter during the creation of "Offline Recurring Contribution" (PP) payment processor.

BASW-169: Removing the financial account from PP payment processor

---

CRM/MembershipExtras/Hook/Links/RecurringContribution.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

The label for the button used to open the list of line items in a recurring contribution should say "View/Modify Future Instalments". 
The end dte on each line item on the list should be the latest end date of related memberships.
Label for the button was "View/Update Recurring Line Items".
End date for each line item was the end date recorded on the membershipextras_subscription_line table.
Changed label for button.
Show maximum end date for memberships on each line item end date.

BASW-212: Fix Labels and End Dates

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php

When the last contribution (payment)  on the payment plan is completed, the payment plan (recurring contribution)  end date is set to match the last contribution (payment) receive date.

BASW-122: Set payment plan end date to match last payment date when its completed

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
css/style.css
js/CurrentPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl

Some minor issues were found testing line item addition for other amounts.
- 'installment' is being used instead of 'instalment'
- Input for item was too narrow
- Input for dates allowed clearing the date
- Tax rates showed '-' by default
- Elements were aligned to top of table row
- When adding a new row, you could still navigate to the other tab and even add a new row.
Implemented fixes:
- Changed 'installment' for 'instalment'
- Made input for item wider
- Removed cross icons to clear dates
- Left tax rate as 'N/A' by default.
- Centered elements vertically on new rows.
- Made tabs unclickable when adding a new row.

BSW-221: Fixes for Donation Line Item Addtion

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

Three issues need to be addressed:
- When a line was added on next period, it was also shown on current period.
- Auto renew column should not be shown if recurring contribution is NOT set to auto-renew.
- If the number of instalments of the payment plan is empty or 0, "membershipextras_subscription_line" with an end date should also be excluded from the view.
- Adding a line item to next period also showed it on current period.
- Auto renew column on line item list was shown, even if recurring contribution was not set to auto-renew.
- If the number of instalments was empty or 0, line items with an end date were being shown.
- Filtered line items shown on current period so they have a start date.
- Auto renew column is not shown if recurring contribution is not set to auto-renew.
- If the …

BASW-212: Fix Listing of Items on Current Period

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

1. Line Items should display with percentage symbol next.
2. If the number of installments of the payment plan is empty or 0, `membershipextras_subscription_line` with an end date should be excluded from the view.
1. Percentage sign does not show next to tax rate.
2. Line items show regardless of if the payment plan has 0 installments and if the `membershipextras_subscription_line`  has an `end_date`.
1. Percentage sign shows next to the tax rate now.
2. `membershipextras_subscription_line` are excluded when the payment plan has 0 installments and the `membershipextras_subscription_line`  has an `end_date`.

BASW-217: Fix View Modify Future Installments Action - Next Period

---

CRM/MembershipExtras/Upgrader.php
xml/customFields_install.xml

1. Creating a custom fieldset "Related Payment Plan Periods" for recurring contribution entity. It should contain two read-only integer fields:
- Previous Payment Plan Period
- Next Payment Plan Period
2. We need to also add this to an upgrader which is only run when upgrading process.
Feature was not present.
Feature has been implemented.

BASW-264: Payment Plan Period Links

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php

When a payment plan is marked as completed, all subscription lines that meet the below conditions should have their end date set to the payment plan end date:
1. start date is not empty
2. end date is empty
Action did not exist
When a payment plan's status changes to `Completed`, all subscription lines matching the criteria in the overview above are have their `end_date` set to the payment plan's `end_date`

BASW-256: Set Subscription Line End Date

---

CRM/MembershipExtras/Upgrader.php

We need to check the extension's process to see if any of the scheduled jobs created by the extension are automatically turned on during the installation process.
We need to make sure all scheduled jobs created by these extensions are turned off by default.
Jobs created by this extension were enabled by default after installation
Jobs created by the extension are now disabled on extension installation.

ASE-257: Ensure Created Jobs are Disabled

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php
js/NextPeriodLineItemHandler.js

We need to change the logic used in "Renew offline auto-renewal memberships" scheduled job, so it finds and processes any recurring contribution that meets all following conditions:
- it is using an offline payment processor (payment manual class)
- has an end date
- it is set to auto-renew
- it is not in status cancelled
- number of instalments is not 0 or null
- its "Next Payment Plan Period" is empty
- has any linked membership that meets the following conditions:
-- end date is equal to or smaller than today
-- the membership's type matches with any "membershipextras_subscription_line" that is auto-renew and not is_removed
If the job finds any payment plan that meets these conditions:
- A new recurring contribution should be created using the existing recurring contribution as a …

BASW-261: Adjustments for Auto-renewal of Payment Plans with Instalments

---

CRM/MembershipExtras/Hook/Post/LineItem.php
CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php
CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
membershipextras.php

When "Renew offline auto-renewal memberships" scheduled job is run, any payment plans that meet criteria to auto-renew and have a number of instalments less than or equal to 1, should use line items on membershipextras_subscription_line to determine the line items for the new contribution.
For each membershipextras_subscription_line which is auto-renew and not is_removed in the recurring contribution, the system should:
- Make a copy of the linked line item and link it to the recurring contribution
- Make a copy of the membershipextras_subscription_line, linking it to the recurring contribution and making the start date of the copied membershipextras_subscription_line be the received date of the last instalment plus one interval. the end date should be empty.
- The end date of the …

BASW-262: Update Renewal with No Instalments to Use Subscription Line Items

---

CRM/MembershipExtras/Hook/Post/LineItem.php
CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Service/MembershipInstallmentsHandler.php

In the auto-renew process, if price auto-update is turned on and a membership is not opt-out of the price auto-update, the new line items created for the new recurring contribution, copied from the line items associated to the previous recurring contribution, should update the price to the membership type's latest value.
On renewal, the line items copied from the previous recurring contribution always had the original price set when creating the membership.
The flags for price auto-update and price update opt-out are now checked to calculate the line item's price for line items related to memberships.
Fixed several bugs found when renewing recurring contribution:
- On renewal, line items of the new recurring contribution were duplicated, as they were being added both by renewal line item …

BASW-263: Implement Recurring Line Items Price Auto Update

---

CRM/MembershipExtras/Upgrader.php

1. As a part of phase 3 upgrader, the extension should find all pre-existing offline payment plans and populate the "Offline Recurring Contribution Line Item" information for them.
2. For each pre-existing recurring contribution using an offline payment processor (payment processor with Payment Manual class):
* create a copy of each line item of the last installment contribution
* the contribution_id of the copied line items should NULL
* a record should be created in "membershipextras_subscription_line" table for each of the copied line item:
* contribution_recur_id - the id of the recurring contribution
* line_item_id - the id of the copied line item
* start_date - start date of the recurring contribution
* end_date - end date of the recurring contribution. If empty, leave empty.
* …

BASW-259: Upgrader

---

js/CurrentPeriodLineItemHandler.js
js/NextPeriodLineItemHandler.js

Currently, when clicking on any of those buttons, a .disabled-click class is applied to the tab's <a> elements. The style for that class (grayish color, no pointer cursor) is coming from the membershipextra's own stylesheet.
But the tabs are jQuery UI tabs, and those already provide an api which includes also a disable() method.
When you invoke that method, a .ui-state-disabled class is applied to the tabs, and that class works fine also in shoreditch.
Tabs were disable by adding the `disabled-click` class to <a> elements of all tabs.
Tabs are being disabled by invoking the `disable()` method

BASW-279: Disable Tabs With Jquery API

---

membershipextras.php

Creation with payment plans with only one instalment was not creating the associated recurring contribution. This has been fixed in phase-3 workbranch by means of PR #80 , but we need to have this fix as part of forth-coming release.
Creation with payment plans with only one instalment was not creating the associated recurring contribution. This was because only payment plans with more than one instalment were being processed. 
##After
Fixed by changing condition to have at least one instalment.

DD-58: Fix Payment Plans with 1 Instalment Creation

---

js/NextPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

Issues reported
1. When "Add Membership" is clicked, the Financial Type column still says "select a membership type" even when an item from the dropdown has been selected - [Screenshot here](http://nimb.ws/cJfPs4)
2. When "Add Membership" or "Add Other Amount" is clicked, other buttons are still clickable even though they shouldn't be. - [Screenshot here](http://nimb.ws/Unc6FI)
3. "Add Membership" and "Add Other Amount" buttons are not compatible with Shoreditch
Points above have been fixed.

BASW-222: Fix Add Membership Line to Standard Multi-line Membership Order (Next Period)

---

CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

When creating a membership and paying for it with a single instalment, offline auto-renew payment
plan, two recurring contributions were being created. 
The problem occurred becuse the logic to determine if the membership was a payment plan was checking if instalments for it were more than one, excluding plans with instlments = 1. This falsely led the system to believe the payment plan was a renewal, creating second recurring contribution for it.
Fixed by changing logic to check for instalments > 0, instead of > 1. Also fixed a syntax error on the PaymentPlanToggler template file.

BASW-67: Fix Double Recurring Contribution on Single Instalment Payment Plans

---

css/style.css
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

Fix Shoreditch compatibility issues like
1. Flashing Row
2. Line Buttons appearing too close to the table header when table is empty
3. Next Period tab Line buttons appearing very off-styled on Shoreditch

BASW-281: Fix Shoreditch Compatibility Issues

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
membershipextras.php

When editing a pending contribution for a payment plan with a single instalment, and that payment plan corresponded to a membership with an overridden status, the recurring contribution was being set as Completed. This should not happen on payment plans with only one installment.
When editing a contribution for a payment plan membership with an overridden status, the system took a different path to update payment info, including a method run when a contribution is updated and its status is changed, affecting its recurring contribution:
https://github.com/civicrm/civicrm-core/blob/5.6.1/CRM/Contribute/BAO/Contribution.php#L242
https://github.com/civicrm/civicrm-core/blob/5.6.1/CRM/Contribute/BAO/ContributionRecur.php#L850
This method checked the recurring contribution and changed its …

BASW-122: Fix Problem When Completing Payment

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
membershipextras.php

When editing a pending contribution for a payment plan with a single instalment, and that payment plan corresponded to a membership with an overridden status, the recurring contribution was being set as Completed. This should not happen on payment plans with only one installment.
This fix was done on master branch on PR #97 and now needs to be included in phase 2 workstream.
When editing a contribution for a payment plan membership with an overridden status, the system took a different path to update payment info, including a method run when a contribution is updated and its status is changed, affecting its recurring contribution:
https://github.com/civicrm/civicrm-core/blob/5.6.1/CRM/Contribute/BAO/Contribution.php#L242
https://github.com/civicrm/civicrm-core/blob/5.6.1/CRM/Contribute/BAO …

BASW-122: Fix Problem When Completing Payment - Phase 3

---

CRM/MembershipExtras/Service/CycleDayCalculator.php
CRM/MembershipExtras/Service/InstallmentReceiveDateCalculator.php

If we have a membership set to be autorenewed and connected with a payment plan with start date = 01/01/2017 with 12 installments paid monthly, the last contribution receive date in this case will be 01/12/2017 and the cycle day will be at this case  = 1 which represents the first day of the month, Now suppose at some point the user edited the payment plan cycle day to 15 (which will represent the 15th day of the month), In this case and at the time of the membership renewal, the  newly created payment plan first contribution will receive date will be 01/01/2018 and the last one will be on 01/12/2018, but this is not correct and it should be 15/01/2018 and 15/12/2018 respectively.
In other words, the calculation should not just be based on the previous payment plan start date but also on …

BASW-68: Correct installment receive date calculation based on the current cycle day

---

CRM/MembershipExtras/Service/MembershipInstallmentsHandler.php

When a membership is signed up with multiple price fields then for a 12 instalment payment plan, only 2 contributions are created, and a DB error is thrown.
This fix was already sent to develop branch and now needs on PR #103 and now needs to be added to master branch to deploy to production environments.
When a payment plan was created using a price set, and some of the selected items had tax while others didn't, a financial transaction for the tax was still created for line items without tax, causing the error, as the 'amount' field was not included in the insert query because the value was null for line items without tax. 'Amount' field is defined as NOT NULL in the database.
Fixed by only creating financial item for tax if the line item has a tax amount defined.

ASE-297: HOTFIX! Fix Creation of Payment Plans with Several Line Items

---

templates/CRM/Member/Form/PaymentPlanToggler.tpl

This PR covers the non proportional space between `Number of Installments` and `Intervals` field of `New Membership` form under `Payment Plan` option
before
after
Before
After
Checking the issue. I found out that the issue is not related to the changes of the Shoreditch or some other CSS. The reason of this improper CSS is because the HTML is not consistent.
Between Payment Plan Start Date and Time there are some which are non-breaking space which adds some space letters between the form elements making them look a bit far from each other as compared to Number of Instalments and Intervals which don’t have any in between
Since it is not in Shoreditch. The improper spacing is in vanilla Civicrm as well
The fix was to either
find some generic class which adds margin to the left elements, but …

SHOR-45: Fix HTML for membership extra payment plan form elements

---

CRM/MembershipExtras/Upgrader.php

A typo where a different custom group names was used to check for the existence of "line_item_external_id" custom group before creating it which is fixed below.

Fixing a typo

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
membershipextras.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

When the full number of instalment contributions are marked as completed, the recurring contribution need to be marked as completed too. The recurring contribution end date should also be set to the cycle day of the last interval.
On completion of payment plan, end date was being set as actual date, instead of receive date of last installment of the payment plan.
The recurring contribution end date is now set to the receive date of the last installment.

BASW-122: Fix Recurring Contribution End Date/Status Calculation on Completion

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php

When the full number of instalment contributions are marked as completed, the recurring contribution need to be marked as completed too. The recurring contribution end date should also be set to the cycle day of the last interval. This should only happen for manual payment plans.
Recalculation of status was being done for any recurring contribution, regardless of if it was a manual payment plan or not.
Recalculation of recurring contribution status is done only for manual payment plans.

BASW-122: Only Recalculate Status For Manual Payment Plans

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php

If a recurring contribution using offline payment processor has only one installment, when the first instalment is marked as completed/ partially paid (a payment is recorded), then the recurring contribution should be set to 'In Progress'.
http://nimb.ws/qIQgiV
Calculation of status was only done for recurring contributions with at least 2 installments.
Status is calculated for every manual payment plan, regardless of amount of installments, but the 'Completed' status is only applied to those with at least 2 installments.

BASW-122: Fix Status Calculation of Plans with 1 Installment

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php

If a recurring contribution using offline payment processor has only one installment, when the first instalment is marked as completed/ partially paid (a payment is recorded), then the recurring contribution should be set to 'In Progress'.
http://nimb.ws/qIQgiV
Fixed for develop branch in PR #108 now needs to be added to phase 3 workstream.
Calculation of status was only done for recurring contributions with at least 2 installments.
Status is calculated for every manual payment plan, regardless of amount of installments, but the 'Completed' status is only applied to those with at least 2 installments.

BASW-122: Fix Status of Plan With Only One Installment

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php
CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
membershipextras.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

If a recurring contribution using offline payment processor has a fixed number (e.g. 12) of instalments, when the first instalment is marked as completed/ partially paid (a payment is recorded), then the recurring contribution should be set to in progress. When that number of instalment contributions are marked as completed (a full payment is recorded), the recurring contribution need to be marked as completed too. The recurring contribution end date should also be set to the cycle day of the last interval.
This only applies to recurring contributions using offline payment processor (processor with payment manual class). Also, if the number of instalments is equal to or smaller than 1, the recurring contribution should neither be marked as completed nor having the end date set, but should …

BASW-122: Release of Fixes to Master Branch

---

CRM/MembershipExtras/Hook/Post/MembershipPayment.php
CRM/MembershipExtras/Upgrader.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

As a staff member, I want to record the period of each membership so that I can view the complete history of exact dates of signup, renewal and end, and any gaps in the membership where it is cancelled or paused.
- Every time a new membership is signed up, a new membership period should also be created under that membership.
- Period start date and period end date should be the membership start date and end date.
- Payment entity should be recurring contribution if paid via payment plan. Otherwise it should be contribution.
On membership creation, no period was created.
Implemented a post hook on MembershipPayment entity, so that once all the data for membership and contribution is available, the period is created.

BASW-323: Create Period on Membership Sign-up

---

CRM/MembershipExtras/BAO/MembershipPeriod.php
CRM/MembershipExtras/Page/MembershipPeriod/PeriodsTable.php
css/membershipPeriodsNestedView.css
membershipextras.php
templates/CRM/Member/Page/Tab.extra.tpl
templates/CRM/MembershipExtras/Page/MembershipPeriod/PeriodsTable.tpl
xml/Menu/membershipextras.xml

This PR is to replace https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/114 by following an approach that is more closer to how civicrm core handles nested rows.
As a staff member, I want to see the period of each membership signup and renewal so that I can know the complete membership history of this contact. 
Membership periods should be nested under each membership type where active periods are in black color, past periods are in gray color and inactive periods are in red, the periods should also be ordered by start date in Ascending order.
There is no place to view the current membership periods.
Membership periods can be viewed by expanding the membership type field : 
+ On Legacy screen
+ On Shoreditch screen
- A new getOrderedMembershipPeriods() method is added to …

BASW-338: Allow users to view membership periods in membership tab

---

CRM/MembershipExtras/Hook/Pre/MembershipCreate.php

When a membership is added to a contact, if the contact does not hold any membership of the same type, a new membership should be created. Otherwise the membership with the same type should be extended/updated.
Action did not exists
Creating a new membership for a contact will now create update existing membership (last added membership) of the same membership type or create a new membership.

BASW-321: Different Membership Types of a Contact Should Appear as Different Membership Lines

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

After Auto-Renew job was run, recurring contribution amount was being set as '0.00' in the new recurring contribution entry. On other occasions, the amount was being calculated as the full amount for the membership, instead of the mount per installment.
Line item amount for the new recurring contribution was being calculated as the full amount for the membership. The calculation for the amount per installment was failing as it required access to the number of installments of the new recurring contribution, but the value was not still set, thus returning the full amount.
Also found a problem displaying the line items of completed recurring contributions with more than one installment, as line items with end date were being filtered out.
Implemented use of number of installments from the …

BASW-261: Fix Amounts on Multiple Installment Plan Renewal

---

CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
CRM/MembershipExtras/Hook/Links/RecurringContribution.php
CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php
CRM/MembershipExtras/Hook/Post/LineItem.php
CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php
CRM/MembershipExtras/Hook/PostProcess/RecurringContributionLineItemCreator.php
CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
CRM/MembershipExtras/Service/ManualPaymentProcessors.php
templates/CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.tpl
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

Issues fixed in this PR : 
1- Fixing a typo in "Manage Installments' modal header title, it was written as "Manage Instalment".
2- Changing the date format to comply with CiviCRM output date settings, it was previously use smarty **date_format** but I changed it to use **crmDate** modifier which is automatically output the date based on civicrm output settings. For the start date and since the start date also contains time, I had to use **date_format** first to remove the time part before passing it to **crmDate** .
3- If the admin created an autorenwal membership using the "contribution" option : 
then no **membershipextras_subscription_line** records will be created, that's because  we use the **postProcess** hook on the membership forms to create the auto-renwal recurring contribution …

BASW-212:  Several Fixes

---

templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

The  period end date in "current period" tab still show the time part of the date 
I changed the template to show only the date part.

BASW-212: remove the 'time' part from the period end data view

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
js/CurrentPeriodLineItemHandler.js
js/NextPeriodLineItemHandler.js

When clicking the auto-renew checkbox on a line item in current period that is unset, so that it gets added to next period, a notice with warning sign should appear with text "This membership type is already enrolled in next period." when there is another membershipextras_subscription_line in next period with the same membership type.
A membership type could be added to next period, and then, added to current period without auto-renew. If auto-renew is then set, it resulted line item to be duplicated in next period, as when the auto-renew check-box was set, the line item was added as a donation on next period, instead of a membership. So each time auto-renew check-box was se on, a new line item was added to next period.
Fixed by implementing validation of membership type, so if a line …

BASW-222: Fix Duplicate Memberships on Next Period

---

CRM/MembershipExtras/Hook/Post/ContributionRecur.php
CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php
membershipextras.php

A problem was found when renewing a payment plan, as the end dates for the recurring line items where not set. Currently, these end dates are set by a post hook on the Financial Transaction entity. For some reason, under certain circumstances, this hook is not dispatched, as the flow to update info in CiviCRM core is different.
Editing a contribution and changing its status to completed takes a different path to recording a payment in CiviCRM. This caused that when the Financial Transaction Hook was called, the conditions for it to run were not being met, in order to calculate the recurring contribution's end date and status, as also the end date for the recurring line items.
Fixed by moving setting of line item end date to ContributionRecur post hook.

BASW-256: Fix Line Item End Date Calculation on Payments Completion

---

js/CurrentPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

Although existing membership type validation when checking auto-renew box was implemented, you could still add a new membership and set it to auto-renew while the same type was present on a line item on next period.
There was no validation of membership type being done when adding a new membership line item.
Fixed by adding membership type validation when clicking on button to add new membership line item.

BASW-222: Validate Membership Types When Adding Line Item

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

The Next Period tab gets removed after the last line item is removed from it. But the Next Period tab should be shown, even if all the line items with “auto_renew“ = 1 are removed. Original spec states Next Period tab should be shown when auto-renew flag is off on the recurring contribution level.
Next Period tab was only being shown if the contact had memberships associated to the recurring contribution. 
Fixed by removing the condition and only showing Next Period Tab if the recurring contribution is set to auto-renew.

BASW-219: Show Next Tab Even if No Mmberships Are set to Auto-Renew

---

js/CurrentPeriodLineItemHandler.js
js/NextPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

Several UI improvements are done to "manage installments" next and current tabs : 
1- When adding a new amount and selecting a financial type that include tax, the tax percentage does not appear on "next period" tab which is now fixed : 
**Before**
**After**
2- A bit of improvement to the layout of confirmation icons when adding an amount in "next period" tab is done so it match the other places : 
**Before**
**After**
3- A **5** seconds expiration is added to all kind of notifications on next and current period tabs : 
**Before**
**After**

BASW-223: UI Improvements to "manage installments" next and current tabs

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php

Renewals seem to have stopped working on payment test server.
An exception thrown on one of the renewals cause the whole execution to stop, leaving pending auto-renewals after the exception untouched.
Fixed by capturing exceptions in an array and throwing a single exception with the list of problems found when all payment plans have been processed.

BASW-262: Improve Exception Handling on Auto-renewals Job

---

templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

on (next period) tab and when clicking on "adding another amount" button, if the by default selected financial type has a tax, then the tax amount percentage sign will not appear, though this is only happen for the one selected by default, but if it get changed then the percentage sign will appear normally :

BASW-223: (Next Period) tab UI Improvment

---

CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
js/CurrentPeriodLineItemHandler.js
js/NextPeriodLineItemHandler.js

There were several issues present when removing line items from next period, both by using the trash icon on next period or the auto-renew checkbox on current period:
1. ‘is_removed’ in ‘membershipextras_subscription_line’ for the corresponding item should set to True but its still set as ‘0' after removing the line item. 
1. If a payment plan is created without the auto-renew, but is later edited to be auto-renew, all line items that are not removed should also be set to auto-renew.
1. For Recurring Contribution with Null Installment- While trying to select 'Renew-Automatically' checkbox (Auto-Renew was set 'False' before) , the original line item entry is deleted from UI as well as from DB.
1. Below error message is thrown in Current Period always while trying to replicate issue#7 for …

BASW-219: Fix Issues With Line Item Auto-renew and Removal

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

For payment plans with no installments, the next period start data will always be same as the start date of the current period.
*Before*
The formula to calculate the next period start date used to be : 
N = Payment Plan Number of Installments * Payment Plan Frequency Interval
then the Frequency Unit (year, month, week ..etc) will be used to add the N amount to the current period start date, so if N was 1 and The frequency unit was 'Year', then 1 Year will be added to the start date of current period to calculate the next period start date. But Since the number of installments for payment plan with no installments is 0, I changed the code to convert it to 1 so the correct amount of time will be added, since at the end, a payment plan with no installments is a payment plan with 1 …

BASW-212: Fix next period start date for payment plans with no installments

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php
js/CurrentPeriodLineItemHandler.js

If a user tries to add a membership line item to the current period and that membership type is already on next period, the auto-renew checkbox should be disabled and forcibly set to true, before applying changes. Also, when the data is saved, instead of creating a new line item for the membership and disallowing setting it to auto-renew (as the membership type is already on next period), we should use the existing line item and update it so it appears both on current and next periods.
When adding a membership to current period with auto-renew, the system checked if the membership type was on next period and if so, issued a warning and disallowed the creation of the membership unless the auto-renew checkbox was unset.
System checks if membership type is already on next period when …

BASW-222: Disable Auto-renew Checkbox and Re-use Lines Among Periods

---

CRM/MembershipExtras/Upgrader.php

QA reported:
> no records are added in 'membershipextras_subscription_line' table after phase 3 upgrader.
> Table is updated with blank entries though we have records created that match the criteria before upgrading.
This problem is caused by the line `foreach ($$manualRecurContributions as $paymentPlan) {`. Removing one `$` solves the problem.

BASW-259: Fix Upgrader.

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php

When renewing, line items were being created for new memberships (ie. memberships created on next period only), however, these line items were not being set as related to the new membership.
The method that was supposed to return the membership's ID on creation failed to do so, causing line items to have an empty entity_id field.
Fixed by returning the ID for the new membership as set by the API create
membership call.

BASW-415: Fix Membership Line Item Creation on Renewal

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php

Renewing a payment plan with single installments that has line items not set to renew, always had those line items, as if they were always renewed.
Single installment payment plans renewal was only setting end-dates for line items set to auto-renew. This caused lines not set to renew to never have an end date and thus, to always be part of the payment plan.
Fixed by setting end date to all line items in the payment plan, and only renewing those set to renew.

BASW-415: Fix Bug Setting End Date for non Renewable Lines in Plans with Single Installment

---

CRM/MembershipExtras/Upgrader.php

Upgrader fails and exits with the fatal error as reported by QA:
```
Feb 22 14:29:48  [info] $CRM_Queue_Page_AJAX_runNext_error = CiviCRM_API3_Exception: "Mandatory key(s) missing from params array: contact_id, frequency_interval"
#0 C:\MAMP\htdocs\Civi5.6\sites\default\files\civicrm\ext\uk.co.compucorp.membershipextras-master\CRM\MembershipExtras\Upgrader.php(330): civicrm_api3("ContributionRecur", "create", (Array:3))
#1 C:\MAMP\htdocs\Civi5.6\sites\default\files\civicrm\ext\uk.co.compucorp.membershipextras-master\CRM\MembershipExtras\Upgrader.php(353): CRM_MembershipExtras_Upgrader->createCustomValueForPaymentPlan("3")
#2 C:\MAMP\htdocs\Civi5.6\sites\default\files\civicrm\ext\uk.co.compucorp.membershipextras-master\CRM\MembershipExtras\Upgrader.php(402): …
```

BASW-259: Fix Upgrader

---

membershipextras.php

Merging develop branch into phase 3 workstream branch brought a second `membershipextras_civicrm_pageRun()` declaration, used to set-up color management per membership type.
Two declarations of the same method in membershipextras.php caused the error.
Merged the two methods in a single method.

BASW-415: Fix Bug Due to Duplicate Method Declaration

---

CRM/MembershipExtras/SettingsManager.php
CRM/MembershipExtras/Upgrader.php

This PR adds an upgrader for phase 4 that:
1. Create periods table
2. Create settings
3. Create periods for existing memberships
Periods table is already created by `sql/auto_install.sql` which runs automatically.
Upgrader did not exists

BASW-332: Upgrader

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OverdueMembershipPeriodProcessor.php
CRM/MembershipExtras/Service/ContributionUtilities.php
CRM/MembershipExtras/SettingsManager.php
CRM/MembershipExtras/Upgrader.php
api/v3/OverdueMembershipPeriodProcessor.php
settings/PaymentPlan.setting.php

The PR aims to add a feature to memberships and membership periods up to date by adding:
1. a new setting that allows users of the extension to set the number of days after a payment is overdue that a membership period should become inactive.
2. a scheduled job to update membership/period status when overdue by amount of days in setting
Action did not exists
Setting has been added.
Scheduled job has been created

BASW-328: Membership Period Cancellation for Payment Overdue

---

CRM/MembershipExtras/Form/RecurringContribution/AddLineItem.php
CRM/MembershipExtras/Hook/Pre/Contribution.php
CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
membershipextras.php

Several issues were found when testing line item addition to current period of a payment plan:
1.  Tax amount is not added to the adjusted first installment amount.
2. Contribution amount gets changed to old value when it is paid/Completed. Updated amount values based on the newly added line items are not displayed.
The amount set by the user was being used as the line item's complete total, calculating total_amount and tax_amount from it. This caused the total of the contribution to change only by the amount given by the user, as the it was assumed the value given was total + tax.
When a membership line item is added to a payment plan, this membership is added to pending contributions using default memberships price set. This price set is marked as quick_config. When recording a payment, …

BASW-220: Fix Issues When Adding Membership to Current Period

---

CRM/MembershipExtras/Hook/Pre/Contribution.php

Creating memberships now caused contributions to be created with huge amounts.
When creating contributions, calculation of amount on pre-hook was using empty ID to look for line items. This caused all line items to be used to calculate amounts, causing contributions to be created with huge amounts.
Fixed by only doing calculation on contribution update and if ID is not empty.

BASW-220: Fix Calculation of Contribution Amount on Creation

---

CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

Several issues were found testing the addition of line items to next period:
- Current period membership types should not be excluded in the next period, unless they are set to auto-renew.
- User should not be allowed to check "Auto-renew offline" option if "Record Membership Payment?" option is not checked, so an offline Auto-Renew should only work with "Record membership payment" checkbox
- Membership's start date gets changed to contribution's receive date for payment plans with more than one installment when recording payments.
- Do not exclude membership types not set to auto-renew: membership types used in current period were being filtered out of next period.
- Don't allow checking auto-renew if no payment is being made: Record membership payment box and auto-renew box were not …

BASW-222: Fix Issues Adding Lines to Next Period

---

js/CurrentPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

When adding  new donation to a payment plan not set to auto renew, tax rate was not being shown.
Some variables that were defined on next period tab were needed for some events happening on current tab, like renewing and adding a new donation. 
Fixed by adding the variables to current tab and using them within the current period handler class.

BASW-212: Fix JS Errors Adding/Renewing Lines On Current Period

---

CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php
CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessor.php

Membership with Auto-Renew as 'False' is not showing up in Manage Installment popup. No line items are displayed in the popup.
Plans that were not auto-renew didn't go into auto-renew setup psto hook, which is where line items were being created for the payment plan.
Move line item creation to where recurring contributions were created, both when adding a membership and renewing.

BASW-212: Create Subscription Lines for Plans not Set to Auto-Renew

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php

Adding a non-renewable membership line item to a plan set to AutoRenew is showing the non-renewable as auto-renew in Membership Tab
When creating membership line items, only the plan's auto-renew flag was checked, to decide if it should be set to auto-renew or not.
Both plan and line item flags are checked to decide if the membership should be set to auto-renew.

BASW-220: Only Set Membership to Auto-renew if Line Item is Autor-renew

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
js/NextPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

User is allowed to add the same membership type in Current period again, hence duplicate entries.
The two period tabs use a generic method to get their membership types which returns pretty much the same membership types irrespective of the tab.
Fix by separating the call the get membership types used to populate the line item creation form of the respective tabs. When on current period, get all membership types whose organisation is not in a membership associated with the recurring contribution (set to auto renew or not).
On the next period, get pretty much the same membership types but include those whose associated recurring contribution to not set to auto renew.

BASW-222: Fix Issue Allowing for Creation of Line Items with Duplicate Membership Type

---

CRM/MembershipExtras/Hook/Post/MembershipPayment.php
CRM/MembershipExtras/Hook/Pre/MembershipCreate.php
CRM/MembershipExtras/Hook/Pre/MembershipPeriodUpdater.php

A- 
1- Create a membership with start and end dates in the past and completed contribution.,
2- Create same membership type again with today date as the new start date but keep the join date the same as the previous one and set the contribution as pending. 
3- As expected,  no new membership will be created, but the previous membership start date and end date will be updated to match the newly created one  dates even though the newly created contribution was set  pending. 
The steps above should only create an inactive membership period with the dates of the membership created at step 2. and only upon completing the contribution the membership dates should be updated as well as the period.
B- 
Doing the same steps above but instead of setting the contribution to "pending" at step 2, set …

RSE-63: Fixing period dates when adding membership with the same type as existing one

---

CRM/MembershipExtras/BAO/MembershipPeriod.php
CRM/MembershipExtras/Page/MembershipPeriod/ContributionList.php
CRM/MembershipExtras/Page/MembershipPeriod/ViewPeriod.php
CRM/MembershipExtras/Page/MembershipPeriod/ViewPeriodDataGenerator.php
templates/CRM/Member/Page/Tab.extra.tpl
templates/CRM/MembershipExtras/Form/MembershipPeriod/EditPeriod.hlp
templates/CRM/MembershipExtras/Form/MembershipPeriod/EditPeriod.tpl
templates/CRM/MembershipExtras/Page/MembershipPeriod/ContributionList.tpl
templates/CRM/MembershipExtras/Page/MembershipPeriod/PeriodsTable.tpl
templates/CRM/MembershipExtras/Page/MembershipPeriod/ViewPeriod.tpl
xml/Menu/membershipextras.xml

Some problems were found when working with view/edit forms on the new membership periods entity.
View Membership: 
1. 'Estimated Legacy Period' should have a '?' in the field label. Should be 'Estimated Legacy Period ?'
2. Time value should not be displayed in Start Date & End Date fields.
3. Info message for 'Estimated Legacy Period' should be corrected as below.
4. 'Recurring Contribution' subheading should be 'Recurring Contributions'. Letter 's' is missing.
5. Can each Contribution have a tag as '(Recurring)' under each as displayed in Contribution tab view if its a recurring.
6. 'Delete' is missing for Completed contribution . Also 'More' or 3 dots option is missing for Pending contribution.
7. View Membership period heading should have 'Membership Type' & Term Details (Period 1, …

RSE-75: Fix Issues on View and Edit Period Forms

---

CRM/MembershipExtras/BAO/MembershipPeriod.php
CRM/MembershipExtras/Form/MembershipPeriod/Activation/Activate.php
CRM/MembershipExtras/Form/MembershipPeriod/Activation/Base.php
CRM/MembershipExtras/Form/MembershipPeriod/Activation/Deactivate.php
CRM/MembershipExtras/Form/MembershipPeriod/Activation/PreChangeWarnings.php
CRM/MembershipExtras/Form/MembershipPeriod/EditPeriod.php
api/v3/MembershipPeriod.php
js/NextPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Form/MembershipPeriod/Activation/Activate.tpl
templates/CRM/MembershipExtras/Form/MembershipPeriod/Activation/Deactivate.tpl
templates/CRM/MembershipExtras/Form/MembershipPeriod/EditPeriod.tpl
xml/Menu/membershipextras.xml

1- We added a confirmation popup when activating or deactivating periods through the quick action menu, but this confirmation popup does not appear when activating or deactivating periods from the period edit form.
2- if there is only one period, then deactivating that period should set the membership status to pending if the status is not overridden.
Both issues are fixed in this PR : 
I added a listener to the "is active" field so it prevent the edit form submission when submit button is clicked (with preventDefault()) and show the confirmation popup using CRM.confirm().
I also added a new url "civicrm/membership/period/preactive-validation" that takes the period id and the new activation status and return the confirmation message  that is needed to be shown to the user.
I also added a …

RSE-62: Adding confirmation popup to period edit form and fixing the membership status update

---

CRM/MembershipExtras/BAO/MembershipPeriod.php
CRM/MembershipExtras/Form/PaymentPlanSettings.php
CRM/MembershipExtras/Hook/Post/MembershipPayment.php
CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
CRM/MembershipExtras/SettingsManager.php
membershipextras.php
settings/PaymentPlan.setting.php
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.hlp
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.tpl

A new setting is added called "**Payment methods that always activate memberships**"
which allow users to select one or more payment method.
If any membership is created or renewed with such payment method then it will activate the membership as well as the newly created membership period, and completing the pending payment after that will not result in extending the membership again.
The PR is divided into two parts, the first part add the setting itself and the code that manage its storage and UI: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/180/commits/72cf1e142ed5db63037120e7831b2e72d7d23d88
and the other part implement the business logic around it : https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/180/commits/15a572ebdfb15039f7edbd684f0dab2463f7 …

RSE-66: Adding/Implementing the (payments that should always activate membership) setting

---

CRM/MembershipExtras/Form/MembershipPeriod/Activation/PreChangeWarnings.php
templates/CRM/MembershipExtras/Form/MembershipPeriod/EditPeriod.tpl

The activation/deactivation dialog looks different when doing it through the period edit form versus using the activation/deactivation quick-action buttons.
*Quick action button dialog*
*edit form dialog*
UI on both dialogs look the same

RSE-62: Unify the activation/deactivation dialogs UI

---

CRM/MembershipExtras/Form/PeriodRules.php
settings/PaymentPlan.setting.php
templates/CRM/MembershipExtras/Form/PeriodRules.hlp
templates/CRM/MembershipExtras/Form/PeriodRules.tpl

The specs says help texts should be added to two fields on the settings page

RSE-80: Add help text

---

CRM/MembershipExtras/Form/MembershipPeriod/Activation/PreChangeWarnings.php
templates/CRM/MembershipExtras/Form/MembershipPeriod/EditPeriod.tpl

As per QA report:
1. Time value is displayed on the popup still while Activating Membership period. It looks good while doing deactivation. Please check below
2. Can you also Left align 'Cancel' button.

RSE-62: Fix Activation Modal

---

CRM/MembershipExtras/Page/MembershipPeriod/PeriodsTable.php
templates/CRM/MembershipExtras/Page/MembershipPeriod/PeriodsTable.tpl

This PR fixes the alignment and date format issue on membership types Period tables
Since the action options were added as part of HTML the indentations and newlines were adding some extra white spaces in the `view/edit` link.
So to make sure the HTML is properly sanitised for browser display and to maintain standards the action links are produced using `CRM_Core_Action::formLink`.
This changed approach fixes the extra space and misalignment of action links and dropdown
Also, for fixing date format `CRM_Utils_Date::customFormat` is used and standard date format `'%Y%m%d'` is used.

RSE-288: Fix style issue with the periods table on membership types

---

templates/CRM/Member/Page/Tab.extra.tpl

This PR fix the multiple accordion icon issue on contact membership page while clicking on edit membership link
For `templates/CRM/Member/Page/Tab.extra.tpl` file inside `addMembershipPeriodsView` function (which is responsible for adding icon to the membership label) while fetching **label** variable in n [this commit](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/72a4b27b#diff-849d196c322e495073d55e5ea8d3bc9aR16) the value was fetched using `.html()` function. This in return was fetching the whole HTML (including the HTML for the icons which was adding new icons for it) . 
Changing the `.html` with `.text` fixed the issue as using this only fetched the label string and not the whole HTML.

RSE-155: Fix multiple icon issue on ajax edit form for edit membership option

---

CRM/MembershipExtras/BAO/MembershipPeriod.php
CRM/MembershipExtras/Hook/PostProcess/ContributionForm.php
CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
CRM/MembershipExtras/SettingsManager.php
membershipextras.php

Message shown when updating a pending contribution for a payment method set to auto-complete was erroneously informing the user that the end date of the membership was changed, by a whole period.
The message was being generated deep within CiviCRM Core when processing the Contribution Form. It erronously took the updating of the contribution as an intent to renew the memberhip, and thus calculated a new end date by extending it for a full period. Periods remained unchanged, as they should, but the message still showed the wrong date.
The new end date is calculated here:
https://github.com/MiyaNoctem/civicrm-core/blob/master///CRM/Contribute/BAO/Contribution.php#L1908-L1912
The message is built here:
https://github.com/MiyaNoctem/civicrm-core/blob/master/CRM/Contribute/Form/Contribution.php …

RSE-66: Fix Message After Updating Pending Contributions

---

templates/CRM/Member/Page/Tab.extra.tpl

In the memberships tab, if the membership edit page get open twice or after expanding the periods nested view then the date selector in date fields in the edit page will be broken and the periods view will keep getting duplicated every time the edit page is opened.
Because we were using the extra.tpl (https://docs.civicrm.org/dev/en/latest/framework/templates/#appending-jquery-or-other-code-to-a-template) way to add Javascript to the membership tab (to handle the periods nested view), and because the edit page and the tab view page share the same core template, the script were getting executed again and again everytime the edit page is get opened, I resolved the issue by preventing the script from running if the page that triggered it is the edit form page.

RSE-71: Resolve UI issues when opening membership edit page

---

CRM/MembershipExtras/Upgrader.php

During running the extension upgraders, an issue saying "missing from params array 'custom_group_id'"
The CustomField API does not know a field with such name and it except a `custom_group_id` field instead (which is the field that accept the custom group name that we need to add the custom field to)

CGP-1451: Fixing upgrader fail during custom fields creation

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

On our instalment management screen, we are able to specify start date and end date when adding a membership line. The start date and end date will control two things:
1. narrowing down the instalments that the new membership line should apply to
2. setting the start date and end date of the membership
We want to avoid setting the end date of life memberships but also not taking away the ability to perform point 1 and 2 for other memberships.

BASW-289: Do not save end date for lifetime meberships.

---

templates/CRM/MembershipExtras/Form/PeriodRules.hlp

This PR fixes a typo issue created on #183 
Pointed out by the comments:
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/183#issuecomment-527201924
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/183#issuecomment-527202585

RSE-80: Fix help text typo

---

CRM/MembershipExtras/Hook/Links/RecurringContribution.php

since there are still some issues with it and it is not important for the next release we are hiding the ability to allow users to modify payment plan line items (by commenting out the hook that add the menu).

CGP-1470: Disabling the ability to modify payment plan line items for the upcoming release

---

CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessor.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php

Renewal of payment plans with only one installment were failing completely.
Recurring contribution for payment plans with at least one installment (ie. > 0) were being created on first contribution's pre hook. But line items for the recurring contribution were being created only for payment plans with multiple installments (ie. > 1) on the form's postProcess hook. Payment plans with 0 or null installments had their recurring contribution and its line items created on the form's postProcess hook too. Thus, plans with only one installment never had their line items created.
Refactored creation of line items for payment plans so line items are created both for single and multiple installment plans, only adding subsequent contributions for multiple installment plans.
Also fixed a bug on job …

CGP-1466: Fix Renewal of Plans with Only One Installment

---

CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessor.php

Injected error by changing the method's name, but failing to do so on method calls.
Call to method and method names were different.
Changed method name to original name.

CGP-1466: Fix isPaymentPlanPayment Method Name

---

CRM/MembershipExtras/Hook/Pre/Contribution.php

Renewal of payment plans resulted in the new contributions having wrong amounts, as if taxes had been applied twice.
Problem was caused by a pre hook on the Contribution entity to fix contribution amount from all line items associated to the contribution. We implemented this on this PR #157 to fix contribution's amount when adding new line items to the payment plan. 
However, adding amounts when they were not being updated caused line items to be re-calculated by CiviCRM core, using the total amount of the contribution (ie. with tax) as the total for the line item, and calculating tax again from it.
Fixed by only fixing contribution totals if set.

CGP-1466: Fix Taxes Applied Twice to Renewal Contributions

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php

Once a payment plan with one or null installments has met conditions to be renewed, the system will create a new pending contribution for renewal each time the auto-renewal job is run. This should not happen. Furthermore, if a membership is created in the past (so that it could meet criteria to be renewed) with a pending contribution and renewal job is run, it’ll create a new pending contribution.
Payment plans with 1 or less installments were being renewed even if an outstanding contribution was pending.
Added logic to query that obtains list of plans with 1 or less installments so it filters out plans with pending contributions.

CGP-1473: Add Fix so No Plans With Pending Contributions Are Renewed

---

CRM/MembershipExtras/Upgrader.php

Running upgrader on a site with many existing payment plans (over 3000) took an inordinate amount of time (over 20 min) and resulted in hundreds of thousands of line itmes to be created, all associated to a single payment plan.
Method that obtained the last installment of a payment plan, in order to fetch its line items and duplicate them for the recurring contribution, failed to return the installment's information. This caused a NULL value to be used to obtain line items by searching by contribution ID, which caused ALL line items in the system to be used for every payment plan.
Fixed by returning the contribution's data so it is available to obtain line items.

CGP-1450: Fix Bug on Upgrader Causing Multiplication of All Line Items

---

CRM/MembershipExtras/Upgrader.php

When running upgrade, none of the payment were processed to create their recurring line items.
Call to obtain last installment was not using the 'sequential' flag, so array with results was indexed with the contribution's ID, but the method was returning the unexisting '0' index of the array.
Fixed by adding the sequential flag. Also used array_shift() to obtain the first element, instead of relying on array keys.

CGP-1450: Fix Call to Obtain Last Installment of PP on Upgrader

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Upgrader.php

After upgrading, payment plans with multiple installments were not upgrading, even if the apparently met criteria to renew.
When upgrading, a new custom group, payment_plan_periods, is added to the recurring contribution entity. For existing payment plans, records for this new custom group are created, and initialized by setting the 'next_period' and 'prev_period' fields to 0. This caused a problem when upgrading old plans, as only plans with next_perio = NULL where being picked for auto-renew.
Problems in upgrader can cause recurring line items to be duplicated, if two simultaneous upgrade jobs are run, for example. These line items then cause exceptions to be thrown when renewing the payment plan, due to a unique key in the line items table.
Implemented fix so payment plans with …

CGP-1450: Fix Renewal of Old Plans With Multiple Installments

---

CRM/MembershipExtras/Upgrader/Setup/PaymentPlanUpdater.php

Payment plans renewing within the next month are skipped from updating, as the idea was they would get renewed by normal upgrader, while all other plans would not be touched. This has changed and now we need to set period links for all plans, making sure only the last recurring contributions of each membership are renewed.
Only plans with end date older than a month were processed.
All payment plans are processed.

CGP-1488: Remove Restriction to Upgrade Old Plans Only

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php

When running the upgrader (or the scheduled job - need to find out which one causing it) all the cancelled recurring contributions are changed to status Pending or In progress. 
When running upgrader, contributions are updated to record links between periods. Doing this was triggering a Pre hook which recalculated the payment plan's status by counting payed contributions, thus breaking cancelled payment plans and setting the as either pending or in progress.
Fixed by only calculating recurring contribution status if current status is eithe Pending, In Progress or Completed.

CGP-1490: Prevent Cancelled Plans From Having Their Status Changed

---

info.xml

We received the following email : 
```
This is a message from the automated release system on civicrm.org.
Congratulations on releasing version v1.0.0 of extension 'Membership Extras'.
Unfortunately we have found a few errors while processing your release:
- The Version Compatibility tag contains an incorrect value
- In info.xml, the element ("documentation") is missing or invalid.
You will need to correct these errors before we can accept this release.
```
which was sent because membershipextras is published on civicrm.org extensions directory.
In this PR I fixed these issues with the XML file

Updating CiviCRM XML file to be compatiable with CiviCRM.org rules for publishing

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

This PR fix the issues with membership types appear in the line item editor if the user wants to add the membership in either current period or next period tabs, it ensure that the logic apply according to following : 
Current Period Tab
-----------------------
- If a membership with certain type is already added, then hide from the select that membership (so the user cannot add the membership twice) and hide any other membership type that belongs to the same organisation (because the customer should not be allowed to have two memberships that belong to the same organisation at the same time)
Next Period Tab
-----------------------
- If a membership with certain type is already added in Current period tab with Auto Renew enabled on it, then it should not appear in the Next tab membership …

BASW-222: Fix what types are allowed to appear in line item editor

---

js/NextPeriodLineItemHandler.js

Users can no longer add future installments inside the manage Next
period screen, and an error in the browser console appears that says :
Invalid financial type id passed
The error is caused by getMembershipType() function inside
NextPeriodLineItemHandler.js file which use JQuery grep() method
to find the matching membership type from nextPeriodMembershipTypes
dictionary which contain the list of membership types for next period,
but grep works with arrays so the function end up returning an empty
dictionary which result in not being able to fetch the financial type
for the selected membership type and thus the error appear.
I replaced the the call to JQuery grep() method with the expression (key
in Dict) to check for the existence of the membership type instead, which fixes
the issue.

BASW-222: Fixing an issue with the ability to add future installments

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

In "Next Period" tab, if a membership get added then it will still appear in the select list which will allow users to be able to add it again and again.
Already added memberships won't appear anymore in the "Next Period" tab

BASW-222: Don't show memberships types that are already selected in next period tab

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php

When the renewal job ran and a payment plan with new donation or event line items got renewed, the new contributions for the next period gor created, with the correct total amounts, but line items different to memberships got skipped. So for example, if the payment plan required 4 line items (two memberships, a donation, and an event), only the two line items for memberships were created for each new contribution of the next period.
A validation was added on renewal job to check line items were not being duplicated, as there is a Unique constraint set on the line items table that will cause an exception to be thrown if a line item for the same contribution_id, entity_table, entity_id, price_field_id and price_field_value_id is added.
Now, price_field_id and price_field_value_id are …

MAE-169: Fix Copying of Donation Line Items to Contributions on Renewal

---

css/style.css
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

Some styling issues with shoreditch needed to be fixed:
1. When clicked on Add other amount on Current Tab, new line caused previous end-dates to wrap.
2. Current Period - 'Select' item & 'Start Date' fields seem to be vertically misaligned.
3. Add a gap after period start date on next period tab.
Styling problems were found on form.
Styling issues fixed.
1. When clicked on Add other amount on Current Tab, new line caused previous end-dates to wrap.
2. Current Period - 'Select' item & 'Start Date' fields seem to be vertically misaligned.
3. Add a gap after period start date on next period tab.

BASW-269: Fix Minor Styling Issues With ShoreDitch

---

CRM/MembershipExtras/Hook/Links/RecurringContribution.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

Issues were found with the dates shown on the View/Manage Future Installments screen.
After Completing All Payments:
- Current Period End Date: Updated to recieve date of last installment, which is not correct.
Period end date being shown on screen was end date of recurring contribution, which starts empty and is finally set when all installments are completed with the recieve date of the last installment.
After renewal, first, membership start date was not being updated to the start date of the new period. Secondly, end date shown on line items was the membership's current end date, which of course, after renewal, changed.
The following example is for a payment plan starting on 2018-01-01, ending on 2018-12-31.
- Period end-date is shown as 31st December 2019. This is wrong, as end date …

MAE-159: Fix Wrong Period Dates Shown After Plan Renewal

---

CRM/MembershipExtras/Hook/Pre/MembershipEdit.php

When recording a payment, membership end dates is getting updated, as if the membership was being renewed. 
We had logic in place on the Membership Entity pre hook to prevent this from happening, but this relied on the fact that the contribution would be updated BEFORE the membership, as we needed the contribution ID in order to determine if the membership was for a manual payment plan and thus prevent membership extension.
Added a condition to the Membership pre hook by checking if the membership is being updated through the record payment form, so that if a payment is being recorded, membership end date extension is also prevented.

CGP-1486: Fix Changing of Membership End Dates on Payment Record

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
CRM/MembershipExtras/Service/CycleDayCalculator.php

When creating payment plan membership (paid with more that one installment), then the receive date day of the contributions other than the first one will always be the 1st day of the month/year ..etc.
When creating the upfront contribution, we calculate the receive date for each one based on the recur contribution cycle day, the cycle day in general is default to 1 in CiviCRM and CiviCRM does not really touch it but we have a code in place to calculate it, but for webforms, the webform will create the prepare the recur contribution params and the cylce day is not include so it will default to 1 and thus causing the issue, in this PR I made sure that the cycle day get calculated inside the recur contribution pre save hook which will correct the issue.

MAE-176: Fix contribution receive date issue when creating memberships with webforms

---

CRM/MembershipExtras/Hook/ValidateForm/MembershipContribution.php
membershipextras.php

We have decided to ignore Auto-Renewal scenarios if Contribution tab is selected as this is not a possible real time scenario.
Currently there are two ways to create Single Payment Membership with Auto-Renew and we need to add a validation to "Auto-Renew offline" field to ensure it cannot be selected if “contribution” tab is enabled:
1. Select Contribution Tab and Auto-Renew Offline
1. Select Payment Plan Tab, 1 Installment 1 Year and Auto-Renew Offline
Added validation on membership creation form so an error message is shown if auto-renew is enabled and it is being paid for with a single contribution from Contribution Tab:
> "Auto-renew offline" is only available for memberships paid with a payment plan. Please choose a payment plan, or uncheck the auto-renew option if the membership …

MAE-189: Validate No Auto-renew for Memberships With Single Contribution

---

CRM/MembershipExtras/Hook/ValidateForm/MembershipUpdate.php
membershipextras.php

Changing a membership's type after it has been created is only allowed by CiviCRM if it is not associated to a recurring contribution (ie. the membership is not auto-renewable). However, we need to prevent this from happenin on non-renewable payment plans too, as changing the membership type will cause several problems on existing installments.
CiviCRM allowed changing the membership type of a membership so long as it was not auto-renewable.
Added validation to membership edit form so that if membership is changed and it belongs to a pyament plan, an error is shown with the text: 
>This membership is part of an ongoing payment plan and cannot be edited directly. To modify the active memberships in this payment plan please go to the manage future instalments screen which can be found as an …

MAE-178: Add Validation to Membership Update Form to Prevent Changing its Membership Type

---

CRM/MembershipExtras/Hook/ValidateForm/MembershipUpdate.php

Validation error is not thrown as expected,
Membership signup with payment plan and without Auto-renew and then change the Membership Type to a different one using 'Edit Membership' form.  Expected validation error is not displayed. Instead it allows the user to edit membership type with a warning message.
When checking if a membership was part of a payment plan, all memberships were determined to be outside of a manual payment plan, due to a bug in evaluating the recurring contribution id.
Fixed bug by using the correct array key to obtain the recurring contribution associated to the membership.

MAE-178: Fix Validation of Membership Type Change

---

CRM/MembershipExtras/Hook/Post/ContributionRecur.php
CRM/MembershipExtras/Hook/PostProcess/RecurringContributionLineItemCreator.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

On Manage Installments screen, membership line start date should be the actual membership start dates and not the received date of the contribution.
While signing up membership using Webforms, received date of DD membership is set based on Payment collection run dates set on DD configuration. But it does affect the membership dates on Manage Installments which is not correct. 
Same issue, if membership is created using 'New membership' or 'Add Membership' option with a different received date, it updates the received date on Manage Installments as the membership start date.
When adding a membership, if the recieve date for the first installment was different to the start date of the membership, the dates shown on the Manage Future Installments Screen showed contribution recieve date as …

MAE-188: Fix Start Dates for Lines Added with Different Recieve Date

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

When you are trying to add a line item on manage installments with a different end date and biggest one, it also updates the end date of existing line items of the recurring contribution. This is working as per the logic - biggest end date among all linked memberships.
But on Membership tab, date values are different.
Largest end date was being used to show as the end date of each line item of the payment plan.
Loaded membership end dates to show them on each line item. Left period end date (ie. largest memberhip end date) as end dates of lines that are not memberships.

MAE-161: Show Membership End Dates Instead of Largest End Date

---

CRM/MembershipExtras/Hook/BuildForm/MembershipEdit.php
membershipextras.php

Users cannot change/override the status of an auto-renewal or payment plan membership after its creation.
Overriding status in membership edit form is available for auto-renewal and payment plan memberships.
The described behavior is something coming from CiviCRM core and was introduced in this core PR : https://github.com/civicrm/civicrm-core/pull/12642
But our workflow in membershipextras extension is different from the core one and overriding the status for such cases should be allowed, which was achieved by basically unfreezing the is_override element which is frozen by default by CiviCRM core.

MAE-192: Allow editing/overriding auto-renewal/payment plan membership status after its creation

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

Period start date for a renewed payment plan with multiple installments should be calculated by using the previous period end date and adding 1 day.
Period start date was being determined by calculating the recieve date of the nth+1 installment. Eg. on a payment plan with 12 installments, the new period's start date would've been the recieve date of what would be the 13th installment.
Period start date is now alculated from the previos period's start date (largest membership end date) and adding one day. If a payment plan is being renewed without any memberships, start date of new perios id still calculated from nth+1 installment recieve date.

MAE-195: Fix Calculation of Renewed Period Start Date

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php

When auto-renewing a single installment membership, the start date remains the same instead of getting updated to reflect the new term start date.
for example, create a single installment autorenewal membership with : 
- start date = 1/1/2017
- end date = 31/12/2017 ( will be set automatically if the membership is 1 year term)
- payment plan start date = 10/1/2017 with frequency 1 Year
after auto-renewal, a new contribution with receive date = 10/1/2018 will be created, where the membership end date will become 31/12/2018, but the membership start date will remain 1/1/2017 instead of 1/1/2018.
Auto-renewing a membership with single installment is also updating the start date of the membership to reflect the new term.
so in the above example, the membership start date will become 1/1/2018 …

MAE-195: Fix membership start date for single installment auto-renewal

---

js/CurrentPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

In manage installments screen, the user can add a membership line with an end date larger than the period end date  (which is the largest date of any membership lines in the period).
If the user tried to add membership line in manage installments screen with an end date that is after the max end date of the period, the following error notification will appear : 
```
Additional memberships must end on or before the end date of the period. Please select a different end date for the membership.
```

MAE-203: Prevent adding additional memberships with end date after max end date of the period

---

js/NextPeriodLineItemHandler.js

In Manage Installments page, when updating “renew automatically” checkbox and click cancel, the selected option is not cancelled
1. Create a membership with payment plan , Auto-renew set & submit
2. Go to Recurring contribution -> Manage Installments and see membership line item is shows with 'Renew Automatically' check box selected.
3. Un-check the 'Renew Automatically' field and see a popup to remove the line item is displayed. Click on 'Cancel' button.
4. 'Renew Automatically' field is still showing unchecked. It should be checked again after cancelling.- Incorrect

MAE-219: Improvements to manage installments UI

---

CRM/MembershipExtras/Hook/Alter/MailParamsHandler.php
membershipextras.php

When you print an invoice of a contribution, today's date is displayed on the invoice instead of the receive date.
CiviCRM always uses current date as the invoice date on the template used to produce the PDF.
Invoice date is set to be the contribution's receive date.

ASESPRT-179: Show Contribution Receive Date as Invoice Date

---

CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlan.php
tests/phpunit/CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlanTest.php

The memberships tab of a contact record has a 'Submit Credit Card Membership' button. Clicking it will open a form to use live payment methods to add a membership. 'Payment Plan' option is displayed. This is not supported for Credit card membership and only 'Contribution' option should be displayed here. 
The same form is used by CiviCRM to show both the offline and on-line membership creation forms. The only thing that distinguishes onw from the other is the use of a 'mode' variable that, in the case of Credit Card Memberships, will hold the value 'live'.
Fix by checking the mode of the form, so that if it is 'live', the payment plan toggle functionality is not added at the buildForm stage.

MAE-242: Stop Showing Payment Plan Toggler on Submit Card Membership

---

CRM/MembershipExtras/Form/RecurringContribution/RemoveLineItems.php

When removing a line item from a payment plan, corresponding lines on installments are left, although their amounts are changed and thus the actual amounts for the contributions show the appropriate value. But if a line is removed from the payment plan, it should no longer appear in the contribution overview. 
When deleting lines from a payment plan, respective lines on contributions on installments were being set to 0 quantity and total. Thus, they still showed on contributions and invoices. This is done as the financial transactions required by civicrm to record the amount change of the contribution require the refernce to the line item
Fixed by doing a soft delete of the line after financial calculations are done by setting contribution_id to null on the line item, thus removing it …

MAE-259: Remove Deleted Lines from Installments

---

CRM/MembershipExtras/Hook/BuildForm/ContributionEdit.php
js/preventCompletingContribution.js
membershipextras.php

Users could complete a single contribution mainly using two methods, either from the contribution edit form or using the "Record payment" option, And since civicrm core runs different code for each method that is becoming sometimes annoying to support both ways, so we decided to minimize the ways in which users can complete contributions so they can now only use the "Record Payment" option to complete contributions.
If the the contribution status is Pending, then you cannot change it to Completed.

MAE-263: Prevent completing the contribution from the contribution edit form

---

CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php

When Cycle Day of a recurring contribution is changed, its start date is not updated.
Changing the cycle day did not update the recurring contribution's start date.
Changing the cycle day will recalculate the start date, based on the new cycle day.
The file CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php had wrong line endings. I separated the line-endings fix in a different commit, and added a second commit with just the fixes done to update the recurring contribution's start date, to facilitate review.

MAE-227: Update Recurring Contribution Start Date on Cycle Day Change

---

CRM/MembershipExtras/Upgrader.php

Currently out the box CiviCRM does not have a status rule configured where the start date is in the future.
With membership extra's there are a few situations where a start date could be in the future:
1. Where a member has signed up and the membership line is planned to start on a future date. This could be on it's own or part of a payment plan.
2. When the automated renewal runs, membership extra will change the start date of the membership to be +1 day from the end date. The issue being that normally the renewal will be configured to run several days before the end date so that invoices are created in good time for the renewal, thus the start date will be in the future.
As such CiviCRM did not have a membership status to give to those memberships.
In the case of 2 above, this was a …

MAE-217: Update membership status rules for future start date cases

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php

After Auto-renewal of Direct Debit memberships, 'Offline Direct Debit Auto-renewal' activity is created for each membership but we should create one activity for each renewed payment plan.
When auto-renewing a payment plan, a hook wes being triggered for each renewed membership in it. This hook was being implemented by DD extension to create activities for the contact to record the memberships' renewal. This resulted in many activities being recorded, cluttering the contact.
Triggered the hook only once, after the payment plan has been removed.

MAE-279: Create Only one Renewal Activity on Auto-renew

---

CRM/MembershipExtras/Form/Contribution/Action/Duplicate.php
CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php
CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php
CRM/MembershipExtras/Service/PaymentPlanStatusCalculator.php
membershipextras.php
templates/CRM/MembershipExtras/Form/Contribution/Action/Duplicate.tpl
xml/Menu/membershipextras.xml

Whilst it was originally specified that the process for retrying a direct debit payment would be as follows:
1- User creates payment batch
2- User submits payment batch using the submit button
3- Contributions are updated to completed status
4- For any failed payments user should update the status manually and set status to cancelled.
5- The batch screen should pick up any payments which are cancelled also so that it can retry
6- If the user does not want to retry then they should cancel the recurring contribution which will ensure that no further payments are displayed in the batch screen regardless of status.
Having discussed, the ability to retry payments with a cancelled status is confusing for users and there are situations where an organisation might want to take a one off payment …

MAE-274: Add contribution action that allows duplicating contributions

---

CRM/MembershipExtras/Form/RecurringContribution/RemoveLineItems.php

Removal would only work if there was a single line that was not a membership, on the payment plan.
When there were multiple lines, the system did not have a reliable way to identify the line that should be removed, thus it chose to skip it, and no lines would be removed from any of the contributions.
Fixed by adding more details to identify the line, and removing the first line found if several meet the criteria. Criteria being used to search for the line item was:
- 'entity_table',
- 'contribution_id'
- 'entity_id'
- 'price_field_id'
- 'price_field_value_id'
I've added:
- 'financial_type_id'
- 'qty'
- 'unit_price'
This way we can better zero-in on the line item that needs to be deleted. This may still yield more than one line item, but as discussed with @jamienovick, we can assume if …

MAE-271: Fix Removal of Multiple Donation Items from a Plan

---

readme.md

We need to update readme files with the details on CiviCRM patches, which ones we're maintaining and why.
Readme implied any ol' CiviCRM after v4.7.x could be used, which is not true for the new version of the extension.
Updated Readme with a section explaining wht versions of patched CiviCRM can bes used, provided links to download, and explained the nature of each patch.
The current state (after changes) of the readme file can be seen here:
https://github.com/compucorp/uk.co.compucorp.membershipextras/blob/262/readme.md

MAE-262: Update Readme With Details About CiviCRM Patches

---

CRM/MembershipExtras/Upgrader.php

The activity types created by this extension are not reserved (by setting is_reserved field value to True) or hidden (by setting filter field value to True), this might allow users to delete these activities types by mistake as it happened with one of our clients.
The existing installation method that creates these activities is updated to make sure they are both hidden and reserved, also a new upgrader is created to make sure that these activities are created with the mentioned filters if they are not already.

BASW-622: Hide and reserve Manage installment activity types

---

.github/PULL_REQUEST_TEMPLATE.md
.github/linters.yml
.github/tests.yml
bin/install-php-linter
phpcs-ruleset.xml
tests/phpunit/bootstrap.php

This PR adds
- Github Actions
- Linters action to run phpcs linters again the php codes that have been added or updated when PR is created.
- Test action to run phpunit tests to run tests against the repository when PR is created. 
- Github Pull Request Template
- PHPCS Ruleset 
This PR also changes the phpunit bootstrap level from classloader to settings, so we could fabricate the CiviCRM settings on unit tests.

MAE-331: Add Linter, Test Actions

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php

This PR changes behaviour of offline auto-renewal job schedule. 
Normally when executing the job OfflineAutoRenewalJob.run to renew memberships offline, the next contribution will be created 
only if the contribution is completed. 
It's very usual (specially in offline payment methods as SEPA bank collections) that the Organizations tries many times to collect a payment and it could last for several weeks to accomplish it (or even until it gets cancelled for any reason). For many organizations that have a monthly basis membership, having the last Contribution still not completed, doesn't mean that the Membership is over, or they cannot try to collect the next payment.
This PR will overcome this issue and will allow next contribution to be created even the last contribution status is not …

MAE-317: Create next contribution when last contribution is not “Completed”

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php

We decided long ago that we are only auto-renewing offline memberships if all the contributions (installments) attached to an expired membership are completed, which means if there is at least one contribution that is still pending then the membership will not auto-renew.
The behavior was revised again and it seems that it is not the case for many organisations, since uncompleted payment does not means  that the membership should end (specially in Direct Debit kind of payments).
In this PR we are changing this behavior so expired offline memberships are auto-renewed even if they have unpaid payments. This also means that if a membership with an end date far in the past (e.g 2017) with a pending contribution is created for whatever reason, so it will get autorenewed each time the scheduled …

MAE-317: Allow autorenewal even if payment plan is still pending

---

CRM/MembershipExtras/Hook/Post/ContributionRecur.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

This PR extends on the work that was done here : https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/276
by fixing some of the issues with memberships autorenewal dates, some of these issues are caused by the PR above and some were there already, the details of these issues and their fixes are explained before.
Also note because many of these issues are strongly linked together, it was hard to separate them into separate commits.
The PR above decided if it should updated the membership start date or not using the new setting inside calculateRenewedMembershipsStartDate() method using the first membership line item it found instead, which will result in updating all the memberships start dates (if there are more than one membership line item) to start at the same time, but …

MAE-348: Fix memberships and payment plan dates after autorenewal

---

templates/CRM/Member/Form/PaymentPlanToggler.tpl

Since CiviCRM 5.25, CiviCRM has changed the currency variable on Membership Form from $currency to $currency_symfol. (see https://github.com/civicrm/civicrm-core/commit/9d3a6f9fa2edf78b14ae35bc045f587b1570883d)
Since Membership Payment Plan screen relies on the currency symbol assign to the membership form.  The variable would need to be updated on Payment Plan Toggle as well.

MAE-364: Change currency variable from currency to currency_symbol

---

info.xml

Updating release info for Membershipextras product suite release version 2.4.0

MAE-384: Bump version and release info for 2.4.0

---

CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlan.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl
tests/phpunit/CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlanTest.php

This PR is to change screen for the Payment Plan Instalment view from number of instalments to schedule.
This PR also removes a logic for the calculation of instalment as part of the UI changes and the schedule calculation will be done in the back end instead of being calculated on the front end and this will be done on the next tickets and pull requests. 
The Schedule field options are displayed based on duration and period type, since the $allMembershipInfo variable does not contain these data, so we need to fetch the membership type details from API when the price set is selected.
There is one falling on a test as the instalment fields is no longer exist in the form and this one will be fixed on another ticket when creating a schedule view.

MAE-379: Create Instalment Schedule view

---

CRM/MembershipExtras/BAO/AutoMembershipUpgradeRule.php
CRM/MembershipExtras/Form/AutomatedUpgradeRule.php
CRM/MembershipExtras/Form/AutomatedUpgradeRuleDelete.php
CRM/MembershipExtras/Page/AutomatedMembershipUpgradeRule.php
CRM/MembershipExtras/SelectValues/AutoMembershipUpgradeRules/PeriodUnit.php
membershipextras.php
templates/CRM/MembershipExtras/Form/AutomatedUpgradeRuleDelete.tpl
templates/CRM/MembershipExtras/Page/AutomatedMembershipUpgradeRule.tpl
tests/phpunit/CRM/MembershipExtras/BAO/AutoMembershipUpgradeRuleTest.php
xml/Menu/membershipextras.xml

Adds a management screen to view membership automated upgrade rules with the ability to disable, enable, delete or edit anyone or change its order. 
We had form to add upgrade rules and to edit them but can only be viewed by accessing the URL directly, and there was no place to view the list of rules added or to quickly disable/enable, edit or delete them.
A new management screen is added with action links to manage these rules, which is accessible from **Administer >> CiviMember >> Membership automated upgrade rules** menu item. the user should have "administer CiviCRM" permission to be able to access it or perform any operation on any rule.

IO-28: Add membership auto upgrade rules managment screen

---

CRM/MembershipExtras/Form/AutomatedUpgradeRule.php
CRM/MembershipExtras/Form/AutomatedUpgradeRuleDelete.php
CRM/MembershipExtras/Page/AutomatedMembershipUpgradeRule.php
templates/CRM/MembershipExtras/Form/AutomatedUpgradeRuleDelete.tpl
tests/phpunit/CRM/MembershipExtras/BAO/AutoMembershipUpgradeRuleTest.php

Fixing some UI issues related to upgrade rules functionality.
1- When trying to delete an upgrade rule, the following confirmation message appears : 
```Are you sure you want to delete this membership automated upgrade rule?```
but it should be : 
```Are you sure you would like to delete the automated upgrade rule?```
2- Clicking on `Cancel` button on create/update/delete forms returns to CiviCRM dashboard screen instead of the rules management screen.
3- Putting a value > 3 in  the "Held For" field will result in not showing the period unit but only its length.
1- 
2- 
3-

IO-105: Fix Upgrade rules UI issues

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

If we have an upgrade rule to upgrade the current membership of type A to a membership of Type B after the current term ends, then it should show that in the "next period" tab inside the manage instalments screen.
Here is an example where we have a membership of type `Student` that should be upgraded to `Student Upgrade` membership after 1 year.
The next period tab showing to what type the membership should be upgraded to :

IO-73: Show upgraded membership in manage installments next period tab

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

In the membership is going to be upgraded next year, then it will only show the correct label in "next period" tab inside "manage instalments" screen, but the rest of the financial values such as the financial type, amount and tax amount will keep referring to the current line item values.
Yearly Payment Plan
Monthly Payment Plan
Yearly Payment Plan
Monthly Payment Plan
hence that the new membership type in the screenshots above has the total price of 100$ and tax rate of 20%

IO-73: Fix upgraded membership financial values in next period tab screen

---

CRM/MembershipExtras/Hook/Post/MembershipPayment.php
tests/phpunit/CRM/MembershipExtras/Hook/Post/MembershipPaymentTest.php

When you try to delete a membership, a popup is shown to confirm the deletion. After confirming, popup keeps on running on the same page and no deletion is happens.
As part of the membership deletion process, all contributions related to the membership are deleted to. After deletion, a post hook is triggered, which in turn executes our Post membership payment hook. This hook used a getvalue API call on the Contribution's entity to obtain the related recurring contribution, however, by this time related contributions had already been deleted. Thus an exception was thrown by the API call.
Changed the API call from getvalue to get, so we can check the count before trying to access the value for recurring contribution ID.

MAE-397: Fix Membership Deletion

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

On our instalment management screen, we are able to specify start date and end date when adding a membership line. The start date and end date will control two things:
narrowing down the instalments that the new membership line should apply to
setting the start date and end date of the membership
We want to avoid setting the end date of life memberships but also not taking away the ability to perform point 1 and 2 for other memberships.
This was previously addressed in this PR https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/192 , but got reverted prior to a release.
Every membership added via the View/Modify Future Installments screen had an end date set when creating/updating.
End date is only set for memberships that are not lifetime.

BASW-289: Avoid Saving End Date for Lifetime Memberships

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php
CRM/MembershipExtras/Test/Fabricator/PaymentPlanOrder.php
tests/phpunit/CRM/MembershipExtras/Hook/Post/MembershipPaymentTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/MultiInstallmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlanTest.php

If you create a renewable payment plan with one membership and multiple instalments, and before renewing you set the membership not to auto-renew, and add a new membership for the next period, once auto-renew runs the amount for the new recurring contribution will be 0, and if you enter the manage future instalments screen, the plan will have no line items for the current period.
When renewing, the start date of the new lines was being calculated by checking the latest end date of all the renewable memberships in the plan and adding a day. Since there are no memberships to be renewed, the start date for the lines was left empty, which in turn caused:
- the amount for the recurring contribution was set to 0, as the calculation only checked lines with start date, 
- the manage instalments …

MAE-401: Fix Renewal of Plans with Only New Membership for Next Period

---

.github/workflows/tests.yml

Currently, when workflow for testing is run. A Drupal site will be created with civibuild was failing due to the recent change on Civibuild 
The reason if the failing is because of a patch for mysql 8 was not properly applied at this point https://github.com/civicrm/civicrm-buildkit/blob/7461255fc26317979c3261e9318d60bbb88bfcd0/src/civibuild.lib.sh#L1051 due to the recent change at https://github.com/drupal/drupal/commit/e1892643309aef2eebbbf646ac568795a8849f85#diff-b63d2c77d41d9f57dc94ede9c21dccd6dacfc89e4e977100af9a447b935c422dR365-R371
A specific Drupal version must be defined to CiviBuild so mysql/database.inc file version will be compatible with the patch. 
This PR is not just for fixing this issue, CiviCRM version is also updated to match the current version of Compuclient.

MAE-416: Update CiviCRM and specify Drupal version

---

CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php
CRM/MembershipExtras/Test/Entity/PaymentPlanMembershipOrder.php
CRM/MembershipExtras/Test/Fabricator/MembershipType.php
CRM/MembershipExtras/Test/Fabricator/PaymentPlanOrder.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessorTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipInstalmentsScheduleTest.php
tests/phpunit/api/v3/PaymentScheduleTest.php

The tests started failing when they are run against the work stream branch after it has merged with the master branch. 
The reason of the test failing is that, recently the Membership Type has been refactored to provide two methods for when creating the Membership Type (API or with BAO class). 
This PR is to fix unit tests related to MAE-380 as well as fix other failing tests as Payment plan form has changed in version 5 workstream. 
The PR also refactors some codes, including changing method name, remove duplicate code and modify  fabricator, fabricator entity for payment plan order 
Tests are failing when running tests after version 5 workstream branch merged with master branch. 
Tests are passed when running tests after version 5 workstream branch merged with master branch. 
There is a …

MAE-380: Fix unit tests after merging workstream branch with master branch

---

CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipEditTest.php

Membership end date is being updated to next period after doing contribution bulk action 'Updating Pending Contribution Status'.
When updating contributions in bulk, CiviCRM will set the num_terms parameter which, in their own words, is used as a "special sauce" to cause the memberships related to the contributions to be extended. Furthermore, this extension is calculated in the membership API call, before hitting the BAO.
https://github.com/civicrm/civicrm-core/blob/master/api/v3/Membership.php#L106-L108
Neutralized CiviCRM API's special sauce, by implementing a pre hook on the membership entity that will unset the end date if it detects a bulk contribution status update is being done.

MAE-283: Prevent Membership Extension on Bulk Contribution Update

---

CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessorTest.php

We need to be sure the cycle day for monthly instalments is assigned according to the Next Payment Collection Run dates available.
For this, a hook was added in #322 , that can be implemented by Direct Debit extension to change the receive date so it matches the next available Payment Collection Run date. In turn we need to make sure cycle day also corresponds to the next available payment collection date.
There were no tests verifying cycle day is calculated from the first instalment's receive date.
Added tests to make sure cycle day is calculated from first instalment's receive date.

IO-124: Add Tests to Check Cycle Day is Calculated From Receive Date

---

CRM/MembershipExtras/Hook/CustomDispatch/CalculateContributionReceiveDate.php
CRM/MembershipExtras/Hook/CustomDispatch/PostOfflineAutoRenewal.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Service/InstallmentReceiveDateCalculator.php
CRM/MembershipExtras/Service/MembershipInstallmentsHandler.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessorTest.php

Direct debit extension needs to be able to change the receive date of the second instalment according to its specified business rules, and every instalment after that, so that the receive dates of each contribution match the available payment collection dates configured in Direct Debit.
Only the receive date for the first instalment could be updated by other extensions.
Added hook when creating the rest of instalments in the payment plan so other extensions can update the receive dates as needed.

IO-126: Hook to Change Receive Date of Second Instalment

---

templates/CRM/Member/Form/MembershipType/Settings.tpl

This PR is to add logic to fix behaviour of Membership Type Setting when Membership Type Plan is set to period. 
Below fields 
- Membership Type Duration unit 
- Fixed Period Start Day
- Fixed Period Rollover Day
were giving the option to select value freely. 
When Membership Type Plan is selected to fixed:
- Membership Type duration unit is set to `1` and then duration interval is fixed to `year` then fields are set to read only. 
- Fixed period start day: Day is set to `1` and disabled. 
- Fixed period rollover: month and day will be set automatically based on selected Fixed period start day and fields are set to read only.

IO-121: Add logic to set setting values for fixed period membership type

---

CRM/MembershipExtras/Hook/PostProcess/RecurringContributionLineItemCreator.php
CRM/MembershipExtras/Service/MembershipEndDateCalculator.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/RecurringContributionLineItemCreatorTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipEndDateCalculatorTest.php

When a membership is manually renewed and changed to a payment plan, the membership end date is increased by a year as expected. But manage instalment start date is using previous year start date still.
The start date used on recurring line items was the original start date of the membership, which did not change as CiviCRM core only changes it if there is a gap in the membership's history.
Used the membership's end date to calculate the projected start date by subtracting the appropriate number of periods as per the membership type's configuration.

MAE-447: Calculate Start Date From Previous End Date on Manual Renewal

---

CRM/MembershipExtras/Hook/CustomDispatch/PostOfflineAutoRenewal.php
tests/phpunit/CRM/MembershipExtras/Hook/CustomDispatch/CalculateContributionReceiveDateTest.php
tests/phpunit/CRM/MembershipExtras/Hook/CustomDispatch/PostOfflineAutoRenewalTest.php

Auto-renewal jobs are failing when there were plans to renew, with the message `Failure, Error message: Errors found on auto-renewals: An error occurred renewing a payment plan with id (X):  is not of type String`.
There was a bug on the PostOfflineAutorenewa hook dispatch class, that was using class attributes that didn't exist to be sent as the hook's inputs. Thus all were null on every dispatch, causing a query that used them to fail.
Updated the attribute names. Also added tests to verify inputs to the dispatch class arrive ok to the hook's implementation methods.

IO-132: Fix Auto-renewal Job

---

CRM/MembershipExtras/Exception/InvalidMembershipTypeInstalmentCalculator.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
tests/phpunit/CRM/MembershipExtras/API/PaymentSchedule/MembershipTypeTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipInstalmentsScheduleTest.php
tests/phpunit/api/v3/PaymentScheduleTest.php

This PR adds additional tests for quarterly instalment as well as more tests for rolling period membership types to API layer and validation to handle when fixed period membership type and quarterly schedule are passed to schedule instalment class
This PR also adds localisation tag for exception messages.

MAE-381:  Quarterly instalment schedule

---

CRM/MembershipExtras/Hook/PostProcess/RecurringContributionLineItemCreator.php
CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
CRM/MembershipExtras/Service/MembershipEndDateCalculator.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/RecurringContributionLineItemCreatorTest.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipEditTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipEndDateCalculatorTest.php

Renewing fixed memberships with only 1 instalment in a payment plan was not changin the end dates, if the contribution was left Penfing.
We were actually treating payment plans in such a way, only plans with multiple instalments updated their end date when renewed via manua renewal option.
Fixed by relaxing the conditions to renew, so that any payment plan extends end date on renewal.
Added a test to verify the scenario.

MAE-427: Fix Manual Renewals

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

Inactive memberships will appear in the manage instalments screen in both current and next instalments tabs : 
Inactive memberships are no longer appear in manage instalments screen  :

ASESPRT-316: Hide inactive memberships in manage installments screen

---

CRM/MembershipExtras/API/PaymentSchedule/Base.php
CRM/MembershipExtras/DTO/ScheduleInstalmentAmount.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
api/v3/PaymentSchedule/Getbymembershiptype.php
api/v3/PaymentSchedule/Getbypricefieldvalues.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl
tests/phpunit/CRM/MembershipExtras/API/PaymentSchedule/MembershipTypeTest.php
tests/phpunit/CRM/MembershipExtras/API/PaymentSchedule/PriceValuesTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipInstalmentsScheduleTest.php
tests/phpunit/api/v3/PaymentSchedule/GetPaymentScheduleTest.php

This PR changes Payment Schedule API response to include the calculation for total instalments amount for the schedule.
The total amount will be set to two different places when schedule instalments is generated. 
- Total amount field which is hidden as this field will be processed by CiviCRM once the form is submitted
- Price value (Total amount) text when price set is being used. 
The PR also updates payment plan toggler UI that includes:
- Handles new response from Payment Schedule API.
- Adds event handler when start date and end date is changed.
- Adds validate to check if selected price values is empty to prevent receiving error from the API if the price value is empty. 
The PR also includes the unit tests for testing calculation of total amount for fixed membership type, rolling …

IO-122: Update schedule API response and payment plan toggler UI

---

CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/AbstractProcessor.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/Contribution.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItem.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/ContributionTest.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItemTest.php

This PR fixes the issue when we set up a membership with price set and the membership is pro rated, the contribution's line item will still hold the original full amount while the total amount of the contribution is the correct pro rated amount. 
This PR also fixes another issue where tax amount is not pro rated when price set is used with fixed period membership type. 
Below before and after screenshots were created with the same membership types and price sets where
- Membership types are fixed period type. 
- Period start day is 01 Jan and Period roll over day is 31 Dec.
- Duration is 1 year.
- Annual Pro-rata calculation is by months.
- Membership start date is today (10-Feb-2021)
Pro rated amounts show on membership sign up page
View contribution shows original  line item and  tax …

MAE-352: Pro rated membership with price set

---

CRM/MembershipExtras/Hook/ValidateForm/MembershipPaymentPlan.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/ValidateForm/MembesPaymentPlanTest.php

This PR adds two custom validations when creating a payment plan when using a price set. 
Unit tests are also added to test validations. 
No custom validations implemented on version 5
Custom validations added to prevent user submit the form that will generate incorrect data. 
The validations are: 
- Validate if the membership period types are mixed of price field values. (rolling or fixed) 
- Validate if fixed period membership type are selected with different period start days

MAE-454: Add validations when creating membership payment plan

---

CRM/MembershipExtras/Hook/BuildForm/MembershipType/Setting.php
templates/CRM/Member/Form/MembershipType/Settings.hlp

This PR adds the default value setting to an Annual Pro-rata Calculation field to a Membership Type Form when creating a new membership type. 
This PR also fixes the typo on the help text of Annual Pro-rata Calculation field.

IO-120: Set default annual calculation setting value

---

CRM/MembershipExtras/Hook/ValidateForm/MembershipType.php
membershipextras.php
templates/CRM/Member/Form/MembershipType/Settings.tpl
tests/phpunit/CRM/MembershipExtras/Hook/ValidateForm/MembershipTypeTest.php

This PR: 
- Adds validate for fixed period membership type when submitting the form and unit tests.
- Moves Membership Type Plan field before Membership Type Duration Unit field.
Validations added are
1. Validate if membership type annual pro rata calculation field is selected when fixed period membership type is selected.
2. Validate if membership type duration is 1 year if fixed period membership type is selected

IO-121: Validate membership type screen

---

CRM/MembershipExtras/Upgrader/Base.php
membershipextras.civix.php

This PR fixes is to updates civix file and an upgrader base class.  The base class and civix file are generated automatically by running `civix generate:upgrader
`
The reason for regenerating the civix file and base upgrader class because CiviCRM changed the way they handle warning for using a deprecated function.  See this [PR ](https://github.com/civicrm/civicrm-core/pull/19256).
The changed will always throw use deprecated warning if the deprecated function is used in anywhere, for example, Drupal module, CiviCRM extension. This would not have an issue we install the extension / module via user interface. However, when we use Drush site-install command to install the Drupal site that ship with a Drupal profile that install the extension when creating a site. 
Any module or extension …

COMCL-101: Regenerate civix file and Base upgrader class

---

CRM/MembershipExtras/Hook/ValidateForm/MembershipPaymentPlan.php
membershipextras.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

Membership Extras version 5 hides contribution received date field on the user interface by default and the default value also set to sign up date. 
This PR adds logic in the interface to assign membership start date onto payment plan start date (first contribution received date) automatically when the payment plan is selected. 
Since Membership extras version 5 is using membership start date as a first contribution received date when creating a new membership, the validation to check that membership start date is required is added to the form on the existing validation Form hook. 
- First contribution receive date in the payment plan is always set as sign up date.
- Membership can be created without select membership start date (civicrm will assign start date automatically based on …

MAE-479:  Payment plan start date

---

CRM/MembershipExtras/Hook/PostProcess/MembershipTypeSetting.php
CRM/MembershipExtras/Hook/PostProcess/UpdateMembershipTypeColour.php
templates/CRM/Member/Form/MembershipType/Settings.tpl

This PR fixes the issue when extended membership type settings have not been saved when creating a new membership type. 
The PR also adds script to the template to hide fixed rollover days when selected fixed membership type to ensure that the field will not show when the page returns from validation if the user selects month as a duration interval for fixed period membership type. 
- Membership type colour and annual pro rata calculation values are only created  into the settings on edit mode. 
- Membership type colour and annual pro rata calculation values are created and updated on when create or update membership type. 
A form object that passes on  CiviCRM postProcess hook does not contain an ID when creating a new object, so the membership  type settings will never be saved. 
In …

IO-121: Save settings when creating new membership type

---

CRM/MembershipExtras/API/PaymentSchedule/Base.php
CRM/MembershipExtras/DTO/ScheduleInstalmentAmount.php
CRM/MembershipExtras/DTO/ScheduleInstalmentLineItem.php
CRM/MembershipExtras/Page/InstalmentSchedule.php
CRM/MembershipExtras/Service/MembershipInstalmentTaxAmountCalculator.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
CRM/MembershipExtras/Service/MembershipPeriodType/AbstractPeriodTypeCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/RollingPeriodTypeCalculator.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl
templates/CRM/MembershipExtras/Page/InstalmentSchedule.tpl
tests/phpunit/CRM/MembershipExtras/API/PaymentSchedule/MembershipTypeTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipInstalmentsScheduleTest.php
tests/phpunit/api/v3/PaymentSchedule/GetPaymentScheduleTest.php
xml/Menu/membershipextras.xml

Total amount and tax amount on currently screen is confusing.  This PR adds line item(s) as sub table on each instalment to visualize financial type, quantity, unit price, sub total, tax amount as total amount similar to CiviCRM contribution line item. 
Line items table works with 
- Rolling membership type
- Fixed period membership type
- Price set with membership type
- Price set with none membership type 
Previously, the instalments display was generated each time by rewriting DOM, this method was expensive especially when we need to rewrite the DOM with nested table each time and the display is not reusable.  
Since, we need a complex table for displaying instalments, the CiviCRM page for displaying the content is created and the membership form is loading the instalments table by …

IO-139: Add Instalment line item(s) to schedule 

---

CRM/MembershipExtras/Upgrader.php

This PR is to change the hook on installation from install hook to post install hook.
The reason for changing is that the tasks for creating default values that created during installation for example membership extras settings and other values may not be available yet for subsequence steps like set default value into the one of the settings. Therefore, the subsequences steps that require settings should be done in the post install hook which is immediately called after installed is done. 
- Install hook was used
- Below error threw when installing the extension with Drush. 
```
User deprecated function: Deprecated Path: There is a setting (membershipextras_paymentplan_default_processor) not correctly defined. You may see unpredictability due to this. CRM_Core_Setting::setItems in …
```

COMCL-101: Use postInstall hook for settings membership extras

---

CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
js/UpdateSubscriptionModifications.js
templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl

On Update Recurring Contribution confirmation dialogue, the button relies on submotOnce function provided by CiviCRM and the function has been removed from CiviCRM Core since version 5.31.0. The PR that updated in the CiviCRM core can be found [here](https://github.com/civicrm/civicrm-core/pull/18410)  and the actual commit [here](https://github.com/civicrm/civicrm-core/pull/18410/commits/f3ec70ebde50948d984632cc83c3425f833f48ca
)  
Since the submotOnce() function was removed, the error is presented when clicked we clicked Yes on the confirmation dialogue.  
This PR fixes that.
This PR also improves the display box to include a warning colour similar to what CiviCRM core does for consistency as well as refactors the code to improve readability of the code and separate js file from the …

MAE-499: Fix Update Recurring Contribution's confirm dialogue button

---

CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipEditTest.php

After updating to CiviCRM 5.35, If we created a payment plan membership with pending status, we found out that the end date will increase each time we recorded a new payment.
Recording a new payment **will increase** the membership end date.
Recording a new payment **will not increase** the membership end date.
This PR https://github.com/civicrm/civicrm-core/pull/18410  to CiviCRM core has the [following change](https://github.com/civicrm/civicrm-core/pull/18410/commits/cbd83ddebb3c7e88157f90905c4ac63bf5214c44) : 
```diff
- $prevnext[] = $this->createElement('submit', $buttonName, $button['name'], $attrs);
+ $attrs['type'] = 'submit';
+ $prevnext[] = $this->createElement('xbutton', $buttonName, $button['name'], $attrs);
```
Instead of creating a button with the value "Record Payment" like …

MAE-492: Fix membership end date after CiviCRM 5.35 update

---

js/paymentPlanToggler.js
templates/CRM/Member/Form/PaymentPlanToggler.tpl

This PR fixes the issue when select membership type then instalments schedule table is shown on the non payment plan tab (contribution). 
Instalment Schedule displays on the contribution tab.
Instalment Schedule displays ONLY when select payment plan tab.
Since we refactored the code and separate the javascript to the different file in this [PR](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/366). 
The constant variables that requires to exist when smart template is completed have not been passed to the javascript in the separate file because they are the indifferent scope therefore, the screen are not working correctly
_How this was addressed?_ 
In order to maintain the javascript logic from the smart template and javascript logic relies on the constant values on the …

MAE-517: Fix schedule instalment display on non payment plan tab

---

js/paymentPlanToggler.js

This PR fixes NaN is assigned when setting a formatted amount more than 4 digits.
When assign formatted amount more than 4 digit, NaN was assigned.
Correct formatted amount is assigned.
Since the totalAmount has already been formatted, calling CRM.formatMoney() to format amount again, it returns NaN when passing the amount that more than 999

MAE-524: Fix contribution amount assigned as NaN

---

CRM/MembershipExtras/Helper/InstalmentCalculatorTrait.php
CRM/MembershipExtras/Helper/InstalmentHelperTrait.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/AbstractProcessor.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/Contribution.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItem.php
CRM/MembershipExtras/Service/MembershipInstalmentAmountCalculator.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
CRM/MembershipExtras/Service/MembershipPeriodType/AbstractPeriodTypeCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/PeriodTypeCalculatorInterface.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/ContributionTest.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItemTest.php

This PR does the followings: 
- Fixed CiviCRM 5.35.1 compatibility. 
- Fixed precision issue on the calculation. 
Issue 1: CiviCRM 5.35.1 
In CiviCRM 5.35,  `membership_id` will not add to parameter when creating contribution / line item objects [Membership.php#L1451)](https://github.com/civicrm/civicrm-core/blob/5.35.0/CRM/Member/Form/Membership.php#L1451), and `membership_payment` record will only be created once the contribution is saved.  However, Membership extras require membership_id to calculate instalment amount and frequency.   
Issue 2: Precision
Membership extras version 5, provides a new UI to visualise the instalment details before the membership is created.  
The instalment details are included instalment amount, tax, total amount as well as sub line item that show the line …

MAE-523: Improve/fix instalment amount calculations.

---

templates/CRM/MembershipExtras/Form/AutomatedUpgradeRuleDelete.tpl
templates/CRM/MembershipExtras/Form/RecurringContribution/Cancel.tpl

After civicrm upgrade the icon of a warning message was broken in the following popups:
1. Recurring contribution -> Cancel dialog.
2. Automated upgrade rule -> Delete dialog.
This PR fixes the issue.
The issue is caused by core style changes (see civicrm/css/civicrm.css). So previously it had styles like these:
```
.crm-container .icon {
background-image: url(../i/icons/jquery-ui-52534D.png);
}
.crm-container .inform-icon {
background-position: -16px -144px;
margin-right: 5px;
}
```
Now it has following styles only:
```
.crm-container .icon {
background-image: url(../i/icons/jquery-ui-52534D.png);
}
```
As background image is a sprite and background position is not set - the first icon becomes visible.
To fix the issue we could add some css, but I've checked warning messages in other …

MAE-513: Fix warning icons in confirmational popups

---

CRM/MembershipExtras/Helper/PaymentPlanTogglerTrait.php
CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlan.php
CRM/MembershipExtras/Hook/PageRun/MemberPageDashboardColourUpdate.php
CRM/MembershipExtras/Hook/PageRun/MemberPageTab.php
CRM/MembershipExtras/Hook/PageRun/MemberPageTabColourUpdate.php
CRM/MembershipExtras/Hook/PageRun/MembershipTypePageColourUpdate.php
CRM/MembershipExtras/Hook/PageRun/PageRunInterface.php
membershipextras.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl
templates/CRM/MembershipExtras/Page/InstalmentSchedule.tpl

This PR fixes the new membership form does not load properly when accessing from Membership Tab in Contact summary page.
In this [PR](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/366), we separated JavaScript functions onto  a JavaScript file, and then we add JavaScript files into the template, so we could separate logics from template. By doing that the JavaScript was loaded property when buildForm hook is called and the JavaScript is loaded into` html-header` region.   
However, when accessing the form as a modal from membership tab on the contact summary page, the html header region has been declared on the main page and therefore CiviCRM ignore this injection.  In order to address this issue, the JavaScript file must be added to `CRM_Member_Page_Tab` in …

MAE-539: Fix new membership screen on memberships tab 

---

membershipextras.php
xml/Menu/membershipextras.xml

Currently, the direct debit configuration can only be accessed with a user that has permission `administer CiviCRM`. In some systems like SaaS platform or even in some organisations, that may not want to give  `administer CiviCRM` to the site administer  but allows access to the certain admin pages and forms.   
This PR adds new `administer MembershipExtras` permission and assign this permission to existing configuration pages that  allows a system admin to assign a new permission to other roles, so the user with the role can access the setting pages without having a global `administer CiviCRM` permission.
Only user that has `administer CiviCRM` permission can access Membership Extras configuration pages.
Either user that has `administer CiviCRM`  or  `administer MembershipExtras` …

CIVIPLUS-176: Add administer Membership Extras permission

---

CRM/MembershipExtras/API/PaymentSchedule/Base.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/Contribution.php
CRM/MembershipExtras/Page/InstalmentSchedule.php
CRM/MembershipExtras/Service/MembershipInstalmentsHandler.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
CRM/MembershipExtras/Test/Helper/PaymentMethodTrait.php
CRM/MembershipExtras/Utils/InstalmentSchedule.php
api/v3/PaymentSchedule/Getbymembershiptype.php
api/v3/PaymentSchedule/Getbypricefieldvalues.php
js/paymentPlanToggler.js
tests/phpunit/CRM/MembershipExtras/API/PaymentSchedule/MembershipTypeTest.php
tests/phpunit/CRM/MembershipExtras/API/PaymentSchedule/PriceValuesTest.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/ContributionTest.php
tests/phpunit/CRM/MembershipExtras/Page/InstalmentScheduleTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipInstalmentsScheduleTest.php
tests/phpunit/api/v3/PaymentSchedule/GetPaymentScheduleTest.php

This PR modifies the custom CalculateContribuitonRecieveDate hook dispatches with an abstract params instead of dispatching contribution object. 
Membership Extras version 5 provides a new payment schedule UI that virtualise the details of instalments that would be created as follow
The existing CalculateContribuitonRecieveDate hook did not support when the payment plan has not been created it yet therefore, the instalment date could not be modified to virtualise on the instalment schedule table. 
This PR fixed that. 
Hook can only be dispatched after the membership form is submitted.
Hook can be dispatched either before and after the payment plan is created. 
The parameter that was passed to the hook was the contribution object and the hook implementer  that modify the instalment date …

IO-136: V5 contribution receive date calculation

---

CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessor.php
js/paymentPlanToggler.js
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessorTest.php

This PR fixes the issue when using renewal membership manually.  
When clicking Renew from the form, the indicator kept spinning due to the error happens in the backend. 
The MembershipPaymentPlanProcessor  and paymentPlanToggler.js designed to use `start_date` field to pass to the API to generate instalments as well as using as the first contribution received date.  The start_date`  field only exists in the new membership form and does not exist in the renewal membership form. 
This PR updates MembershipPaymentPlanProcessor and paymentPlanToggler.js to use  `renewal_date` as contribution received date when using renewal membership form.

MAE-551: Make membership manual renewal screen work with version 5 UI

---

CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl

Since we are going to use 'next scheduled contribution date' field to determine if we should renew a payment plan or not, we want to give users the ability to adjust its value if needed. The work here exposes this field in the payment plan edit form.
The  'next scheduled contribution date'  is not available in the payment plan edit form, and updating the cycle day will affect its value.
The  'next scheduled contribution date'  is available and editable through the payment plan edit form, and updating the cycle day does not affect its value.

MAE-580: Make 'next scheduled contribution date' field editable from UI

---

CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/ContributionRecurTest.php

I here prevent any update to the recurring contribution 'next_sched_contribution_date' field from outside
Membershipextras (Basically preventing CiviCRM core and the webform_civicrm module from altering its value) since it will be used for autorenewal, and thus we need to be able to control its value with external interference. Hence that this only affect offline payment processors (any payment processor that extends the Payment_Manual class).
Creating payment plan from the admin form or from a webform will set the `next_sched_contribution_date` value 
Creating payment plan from admin form or from webform will set the `next_sched_contribution_date` to blank
Hence that this is temporary, and I will later implement new code to set its value but form within Membershipextras, since the value …

MAE-581: Prevent updating 'Next contribution date' from outside Membershipextras for offline payment processors

---

CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessor.php
CRM/MembershipExtras/Test/Fabricator/PaymentPlanOrder.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessorTest.php

Here we set the "next scheduled contribution date"  according to the new v5 specs when creating offline payment plan memberships through the admin form.
Creating an offline payment plan membership through the admin form will result in an empty "next scheduled contribution date"
: 
Creating an offline payment plan membership through the admin form, will result in updating the "next scheduled contribution date" according to the following logic:
- If it is a monthly payment plan (12 installments) with 1-year membership, the date will be +1 month from the last contribution "receive date" in that payment plan.
- If it is a quarterly payment plan (4 installments) with 1-year membership, the date will be +3 months from the last contribution "receive date" in that payment plan.
- If it is a …

MAE-582: Set next contribution date when creating payment plan membership

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstalmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlan.php
CRM/MembershipExtras/Service/CycleDayCalculator.php
CRM/MembershipExtras/Service/InstalmentReceiveDateCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/AbstractPeriodTypeCalculator.php
CRM/MembershipExtras/Test/Entity/PaymentPlanMembershipOrder.php
CRM/MembershipExtras/Test/Fabricator/PaymentPlanOrder.php
CRM/MembershipExtras/Upgrader.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/ContributionTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/MultiInstalmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlanTest.php

Some of the current criteria we have for autorenewal are:
- Are any of the memberships that are attached to the payment plan has an end date that is less or equal today date (with `days to renew in advance` setting in mind).
- Or if there are no memberships attached to the payment plan, then check if there are any active autorenewal subscription line items attached to the payment plan (though to be clear we are not officially supporting payment plans without memberships yet).
And if any of these conditions apply, then we proceed with the autorenewal.
Here I change this to use the payment plan "next scheduled contribution date"  as a condition for auto-renewal, so if this field value is less or equal today date (with `days to renew in advance` setting in mind) then we renew the payment …

MAE-592: Use 'next scheduled contribution date' instead of membership end date for autorenewal

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/MultiInstalmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlanTest.php

On autorenewal, contribution fees are getting copied to the new term contributions, which should not be the case given new terms might get paid using different payment processor and/or payment method.
Contribution fees are no longer copied for the new term contributions.

WHF-175: Don't copy contribution fees from last term on autorenewal

---

CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/UpdateSubscriptionTest.php

As part of the new changes to how the cycle day and the next scheduled contribution date interact for V5, in this PR I am implementing the following:
- Hiding the "Cycle Day" field for annual payment plans in the payment plan edit screen.
- Updating the "Cycle day" for monthly payment plans will result in updating the "next scheduled contribution date" so the day in which it happen will be same as the new "Cycle day".
- Cycle day is visible for annual payment plans: 
- Updating the cycle day for monthly payment plans is not reflected on the "next scheduled contribution date"
- Cycle day is visible hidden for annual payment plans: 
- Updating the cycle day for monthly payment plans is reflected on the "next scheduled contribution date"

MAE-582: Version 5 Cycle day changes

---

CRM/MembershipExtras/Service/MembershipInstalmentsHandler.php
CRM/MembershipExtras/Utils/InstalmentSchedule.php
membershipextras.php

When submitting a direct debit webform and the creation of upfront contributions starts, it results in calling **membershipextras_calculateContributionReceiveDate** hook which results in calling **CRM_MembershipExtras_Utils_InstalmentSchedule::getPaymentPlanSchedule** method that is used to determine the payment plan schedule and then decides if  the direct debit dates calculation logic should be performed or not (since it is only done on monthly payment plans), but because it depends on reading the payment schedule value from the $_REQUEST variable which is only set if the request is coming from the admin form submission, the method end up returning NULL which prevents from running the direct debit date calculation logic on the payment plan, here I changed the method so it determine the …

MAE-609: Fix upfront contributions date calculation for Direct debit webforms

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstalmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlan.php
CRM/MembershipExtras/Upgrader.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/MultiInstalmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlanTest.php

There was a misunderstanding that the trigger for autorenewal should be the next scheduled contribution date. There is a risk that this date may be before or after the end date of the membership (specially in Direct debit payment plans).
As such we changed the "trigger" for the autorenwal job to be the end date of the membership (taking into account the payment plan setting Days to renew in advance), or the minimum membership end date if there are more than one membership in the payment plan with different end dates as it used to be the case before. 
The installments receive dates  is still being calculated based on the next scheduled contribution date,
The next scheduled contribution date is what we use to trigger the autorenewal.
The membership end date (or the minimum membership end …

MAE-612: Changes to autorenewal job trigger and migrating upgrader

---

js/modifyAnnualRecuringContributionPage.js
membershipextras.php

This PR makes the following update on View Recurring contribution form:
1. Hides “Cycle Day” field on 'View Recurring Contribution” form in case of Annual memberships.
2. Change the label name to “ Next Scheduled Contribution Date”.
Cycle Day is not hidden when payment frequency is not annual.

MAE-610: Hide Cycle day and update Next Contribution Label

---

CRM/MembershipExtras/Form/RecurringContribution/AddLineItem.php

This PR ensures that Recurring contribution amount is correct after adding a line item in manage installments view of annual payment plan and that has auto renewal
When calculating new total amount for recurring contribution, ensure that only amount from line items with end_dates are included (Given that the payment has one or no installment). same condition is applied to every other part of the code where total recurring contribution amount is calculated.
```php
$installments = CRM_Utils_Array::value('installments', $this->recurringContribution, 0);
if ($installments <= 1) {
$conditions['end_date'] = ['IS NULL' => 1];
}
```

MAE-619: Fix error with extra amounts being added to total contribution amount

---

CRM/MembershipExtras/Upgrader.php
info.xml
readme.md

Doing a bit of generic non-functional (almost) improvements to Membershipsextras, which are:
- Improving the readme and the info.xml file to specific the compatible CiviCRM version with this extension.
- Changing communication details to include the company new name and email.
- Removing outdated information from the readme file about the core patches.
- Adding an upgrader to disable the core extension "Contribution Cancel Action", which was done originally in Compuclient (see PROD-15 ticket for more details), but I think it make more sense for it to be part of Membershipextras so it applies equaly to anyone who installs or upgrades this extension, given that Membershipextras does not function properly with it being installed.

MAE-497: Documentation and installation improvments

---

CRM/MembershipExtras/Form/RecurringContribution/RemoveLineItems.php

When a membership line item is deleted from the current period tab in the "manage installments" screen, we unlink the LineItem record for this membership from any future pending contribution in the payment plan, but while investigating BASW-897, I noticed that we still keep the MembershipPayment record that links the Contribution with the Membership, and thus if you open the membership that we removed from the current period tab, you will still see that it is linked to the future  pending contribution even though it has no line items on any of these future  contribution, this PR corrects by removing the MembershipPayment Record that links the two.
I used raw SQL query because MembershipPayment API end point does not support the "delete" action.

BASW-897: Remove link between contribution and membership when removing membership line item

---

membershipextras.php

CiviCRM decided to limit the supported entity_table options to some predefined tables as seen in this PR https://github.com/civicrm/civicrm-core/pull/20464, this is now causing error in this extension,  because this extension allow users to add LineItems to civicrm_contribution_recur table which is not part of the predefined tables.
implement the hook_civicrm_fieldOptions hook to add civicrm_contribution_recur to the LineItem options.

PROD-33: Add civicrm_contribution_recur to LineItem supported entity options

---

CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessor.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstalmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlan.php
CRM/MembershipExtras/Service/PaymentPlanNextContributionDate.php
CRM/MembershipExtras/WebformAPI/PaymentPlanNextContributionDateUpdater.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessorTest.php

Fixing how  "next scheduled contribution date" is calculated for fixed memberships payment plans to be based on the membership end date + cycle day, instead of last contribution date.  
As part of of the work we did in MAE-372 Epic, we changed how installments (contributions) "receive date" is calculated upon autorenewal to be based on the payment plan (recurring contribution) "**next scheduled contribution date**" .
But with fixed memberships this result in some problems, here is an example:
1- Create new "Fixed" membership type with duration of "1 Year" and  period start day = "1st of December" and period rollover day  = "30th of November":
2- Create new membership using Membership creation form through CiviCRM, use "Payment Plan" as a method of payment, set Schedule to "Annual, and set …

PROD-57: Fix next scheduled contribution date calculation for fixed memberships

---

.github/workflows/tests.yml
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItemTest.php

- Updating CiviCRM version in tests workflow to match the CiviCRM version on Compuclient 1.29
- After the update, this class tests `CRM_MembershipExtras_Hook_Pre_MembershipPaymentPlanProcessor_LineItemTest ` started to fail:
````
1) CRM_MembershipExtras_Hook_Pre_MembershipPaymentPlanProcessor_LineItemTest::testProRatedPriceSetContributionLineItemOnCalculationByMonthFixedMembershipType
CiviCRM_API3_Exception: passing in incorrect tax amounts is deprecated
/__w/uk.co.compucorp.membershipextras/uk.co.compucorp.membershipextras/site/web/sites/all/modules/civicrm/api/api.php:134
/__w/uk.co.compucorp.membershipextras/uk.co.compucorp.membershipextras/site/web/sites/all/modules/civicrm/tools/extensions/uk.co.compucorp.membershipextras/CRM/MembershipExtras/Test/Fabricator/Base.php:37 …
```

COMCL-169: Update CiviCRM version in tests workflow

---

templates/CRM/MembershipExtras/Page/InstalmentSchedule.tpl

In this PR we add a space` ` between currency symbol and the value in the instalment schedule screen.

WHFSPRT-254: Add space between currency symbol and value

---

js/paymentPlanToggler.js

This PR hides the auto-renew option field when the contribution tab is opened
The auto-renew option field is visible irrespective of the current tab.
The auto-renew option field is only opened when the payment tab is opened. it is hidden by default.

MAE-476: Hides the auto-renew option field when the contribution tab is opened

---

CRM/MembershipExtras/Exception/InvalidMembershipTypeInstalment.php
CRM/MembershipExtras/Hook/ValidateForm/MembershipPaymentPlan.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
tests/phpunit/CRM/MembershipExtras/Hook/ValidateForm/MembesPaymentPlanTest.php

This PR prevents a user from selecting membership types with different `period type` and `duration unit`. should in case a user selects multiple membership types with different `period type` or `different unit` the following error is displayed `You have selected membership types with different period types (i.e. rolling and fixed) and/or different duration units. Please only select memberships with the same period types and duration units.`  
Error `All membership types must have a same period type.` is only displayed when multiple membership types with different period types are selected.
The new error message is displayed when multiple membership types with different `period types` or different `duration units` are selected.

MAE-684: Prevent user from user selecting membership type with different period and duration

---

CRM/MembershipExtras/Exception/InvalidMembershipTypeInstalment.php
CRM/MembershipExtras/Helper/InstalmentValidator.php
CRM/MembershipExtras/Hook/ValidateForm/MembershipPaymentPlan.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
CRM/MembershipExtras/Validate/PaymentPlan/MembershipType.php
js/paymentPlanToggler.js
tests/phpunit/CRM/MembershipExtras/Hook/ValidateForm/MembesPaymentPlanTest.php

Before now, the validation performed in the front-end is different from that performed in the back-end when creating a new membership with a payment plan,  in this PR we ensure the same validation happens on both the front-end and back-end.
It also includes the work done in this [PR](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/423) where we prevent users from selecting membership types with different periods and duration.
Currently, changes in the UI can allow a user to get around the validation, in some cases, this leads to errors, at times the user is able to create a membership with recurring membership bypassing the validation.
Now the validation logic that happens in the backend also happens in the frontend.
We create a new class …

MAE-685: Simplify payment instalment validation logic

---

CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipInstalmentsScheduleTest.php

The instalment dates listed on the new membership screen can sometimes not match the contribution instalment dates after creation, this difference is noticeable when using a day above 28. In this PR we use the same logic used in calculating contribution dates to calculate the instalment dates for the new membership screen.
The instalment dates on the new membership screen.
The new membership screen uses the inbuilt PHP DateTime function to add months to date, and this function behaves in some certain way as we've seen in the screen above, `2022-01-29 + 1month =  2022-03-01` and subsequent months use the day from the previous calculation. 
The actual instalment dates after creation.
Whereas when creating the contributions, the instalment dates are calculated using the custom function …

MAE-751: Consolidate logic for calculating membership instalment dates

---

CRM/MembershipExtras/Upgrader/Steps/Step0009.php

This PR adds an upgrader to update `next_sched_contribution_date` and `cycle_day` for the following specific scenarios:
- frequency unit is monthly and if the `next_sched_contribution_date` day is greater than 28, the upgrader changes the day to 28.
- frequency unit is monthly and if the `cycle_day` is greater than  28, the upgrader changes the `cycle_day` to 28

MAE-740: Add upgrader to update next_sched_contribution_date and cycle_day

---

CRM/MembershipExtras/Hook/ValidateForm/UpdateSubscription.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/ValidateForm/UpdateSubscriptionTest.php

This PR adds new validation to the edit recurring contribution screen, such that the following scenarios would return an error
- frequency_unit is monthly; changing the next_schedule_contribution date to a day after 28 
- frequency_unit is yearly; changing the next_schedule_contribution date to Feb 29
- frequency_unit is monthly; changing the cycle_day to a day after 28
Validation does not exist
A validation error is thrown when any of the invalid scenarios happen:
_frequency_unit is monthly; changing the next_schedule_contribution date to a day after 28_ 
_frequency_unit is yearly; changing the next_schedule_contribution date to Feb 29_
_frequency_unit is monthly; changing the cycle_day to a day after 28_

MAE-739: Validate next_schedule_contribution_date/cycle_day when updating a recurring contribution

---

CRM/MembershipExtras/Helper/InstalmentHelperTrait.php
CRM/MembershipExtras/Helper/InstalmentSchedule.php
CRM/MembershipExtras/Service/CycleDayCalculator.php
CRM/MembershipExtras/Service/MembershipInstalmentsHandler.php
CRM/MembershipExtras/Service/PaymentPlanNextContributionDate.php
CRM/MembershipExtras/Test/Fabricator/PaymentPlanOrder.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessorTest.php
tests/phpunit/CRM/MembershipExtras/Service/CycleDayCalculatorTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipEndDateCalculatorTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipInstalmentsScheduleTest.php

In this PR,
- we add support for multi-year rolling membership
- we add support for multi-month rolling membership
- we ensure cycle day doesn't exceed 28
- we ensure the next scheduled contribution date day doesn't exceed 28
Multi year/month memberships can not be created
Users can now create X year membership and appropriate instalment count for the selected schedule, for example when X is 3, 36 instalments are created for the monthly schedule, 12 instalments are created for the quarterly schedule and 3 instalments are created for the annual schedule.
On renewal, the membership period is extended by the membership duration, and a new recurring contribution is created.
Users can now create X month membership and appropriate instalment count for the selected schedule, for example when X …

MAE-693:  Add support for multi years/month rolling membership

---

CRM/MembershipExtras/Hook/Links/RecurringContribution.php
api/v3/PaymentSchedule/Getscheduleoptionsbymembershiptype.php
js/CurrentPeriodLineItemHandler.js
js/NextPeriodLineItemHandler.js
membershipextras.php
xml/Menu/membershipextras.xml

Users without 'administer CiviCRM' permissions are unable to create payment plans (they cannot select payment plan schedule), and unable to manage payment plans installments using "View/Modify Future Instalments" action. This purpose of this PR is to provide a way for users to do these actions with permissions that give less control over the entire system.
1- If a user with permission to create memberships and contributions ('edit memberships'  and 'edit contributions') which are needed to access the membership creation form, they still won't be able to submit a payment plan membership, due to a missing "schedule" field, and the form will complain about insufficient permission.
2- If the same user tried to use the "View/Modify Future Instalments" action on an existing payment plan, they …

MAE-393: Allow non administers to manage payment plans

---

CRM/MembershipExtras/Service/InstalmentReceiveDateCalculator.php
CRM/MembershipExtras/Service/PaymentPlanNextContributionDate.php
tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/MembershipPaymentPlanProcessorTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipEndDateCalculatorTest.php

Before now, the PHP builtin `date->add` method is used to get the next instalment dates for an annual recurring contribution, in this PR we change this and use the custom logic in `getSameDayNextMonth`. This will enable the proper handling of leap dates.
Also in a [previous work](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/432) we prevented the next scheduled contribution date day from exceeding 28, in this PR we limit it such that this will not affect the next scheduled contribution date day of annual recurring contribution whose month is not February
If the last contribution date is 02/29 - the next scheduled date is 03-01
If the last contribution date is 02/29 - the next scheduled date is 02-28
The next scheduled contribution date of annual recurring contribution …

MAE-769: Use membershipextra custom logic for adding date to calculate next instalment dates for an annual recurring contribution

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

In this PR we return specific fields from the Membership API.
The `modify instalment` page is broken, and the user cannot perform any action.
The `modify instalment` page displays as expected, and the user can perform the expected actions.
Before now when getting related membership of line items, we return every membership field, and these might include attachment fields also, which can break the page. in this PR we limit the returned membership fields to `'start_date', 'end_date', 'id'`.
`'start_date', 'end_date', 'id'` are the membership fields we recognize are required for now.

COMPCRM-58: Return specific field from Membership API

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Service/MembershipInstalmentsHandler.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/MultiInstalmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlanTest.php

Changing how contributions are created after autorenewal, so they use data from the recurring contribution instead of the previous term last contribution. The specific fields we are now copying from the payment plan instead of the last term contribution are:
- currency
- contact_id
- payment_instrument_id
- financial_type_id
- is_test
The reason behind this, is that sometimes contributions might be changed manually by users, or sometimes a contribution might be paid let's say with "credit card" payment method , where the original payment plan was paid by "direct debit" payment method. Thus the recurring contribution is more accurate place to get such information, instead of using the last contribution which is subject to manual changes.
The only things we still copy from the previous …

BASW-928: Use recurring contribution data to create autorenewal contributions

---

.github/workflows/tests.yml
CRM/MembershipExtras/Hook/PageRun/MemberPageTabColourUpdate.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItemTest.php

As part of our plan to move to PHP 8.0, we are updating the unit-tests container to use the PHP 8 version of it. With this PHP update, we are also updating Drupal to version 7.79 and CiviCRM to version 5.51.3.
Doing that resulted in many failing tests, large part of them were fixed after applying this patch to our CiviCRM core:
https://github.com/compucorp/civicrm-core/pull/91
The other issues are fixed in this commit: 
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/443/commits/04c625b11ee8de30f52fda352647662e9e6c96cf
which was caused by `MembershipPaymentPlanProcessor/LineItemTest.php` test trying to access non existent array elements (it used to throw a notice in PHP 7.4, but a warning in PHP8+, which what caused the tests to fail).
While looking around on my local …

MAE-887: Update testing workflow to PHP 8 container and fix failing tests

---

api/v3/OfflineAutoRenewalJob.php

Here we only allow once instance of the autorenewal job to run at any given time, given the renewal might happen more than one time for the same membership if the autorenewal happen to run multiple times simultaneously.
Multiple instances of the autorenewal job could run at the same time, which might cause the same membership to be renewed multiple times.
Only once instance of the autorenewal job can run at any given time:
An error saying:
```
Could not acquire lock, another Offline Autorenewal process is running
```
would show in the job logs for any other instance tries to run while there is a one t hat is already running.
I've used CiviCRM lock manager `Civi::lockManager()` to acquire a lock on the first instance that runs, and that lock is only released when job is done running.

CIVIIB-11: Allow only one instance of auto-renewal job to run

---

CRM/MembershipExtras/Hook/Links/RecurringContribution.php
tests/phpunit/CRM/MembershipExtras/Hook/Links/RecurringContributionTest.php

When a user is about to cancel a recurring contribution, a custom modal is shown to the user, asking if they `wish to cancel any linked membership`, even though the recurring contribution has nothing to do with membership, for example, a recurring contribution for a donation. In this PR we limit this custom cancel modal to a recurring contribution created for membership using a manual payment processor defined in Membership Extras.
The custom cancel modal is always displayed when cancelling recurring contributions.
The custom cancel modal is only displayed when cancelling recurring contributions for a membership plan.
The default modal is displayed for other types of contributions.

MAE-904: Limit when the cancel modal is displayed

---

CRM/MembershipExtras/BAO/PaymentScheme.php
CRM/MembershipExtras/Page/PaymentScheme.php
templates/CRM/MembershipExtras/Page/PaymentScheme.tpl
tests/phpunit/BaseHeadlessTest.php
tests/phpunit/CRM/MembershipExtras/BAO/PaymentSchemeTest.php
xml/Menu/membershipextras.xml

This PR adds a page that display list of payment scheme.  The payment scheme will display by ID in descending order.  
The list page also supports CiviCRM pop-up form when adding or editing the payment scheme. 
The page does not exist. 
[screencast-dev.localhost_8020-2023.02.10-14_07_10.webm](https://user-images.githubusercontent.com/208713/218135067-c3357bb0-88d5-491f-89a1-7dc2cd075b5c.webm)

CIWEMB-100: Add page to list payment schemes

---

membershipextras.php

This PR adds menu to list paymet schemes to CiviCRM admin page
The menu does not exist
Menu added under Administrator -> CiviContribute 
[screencast-dev.localhost_8020-2023.02.22-14_06_43.webm](https://user-images.githubusercontent.com/208713/220644659-9296f4e3-c076-407b-9b7e-ced1ca680ce5.webm)

CIWEMEB-100: Add menu payment scheme menu

---

CRM/MembershipExtras/Form/PaymentScheme.php

This PR adds functionality to edit payment scheme.
Payment scheme could not be editted
Payment scheme can be editted. 
[screencast-dev.localhost_8020-2023.02.22-12_26_21.webm](https://user-images.githubusercontent.com/208713/220620479-112ce167-b854-47a8-9d40-e33414447ac9.webm)

CIWEMB-101: Support editing payment scheme

---

CRM/MembershipExtras/Form/PaymentScheme.php

Add payment processor dropdown menu field where it shows only the payment processor whose type is `GoCardless` to payment scheme form

CIWEMB-135: Add payment processor field to payment scheme form

---

CRM/MembershipExtras/Setup/Manage/CustomGroup/PaymentPlanExtraAttributes.php
CRM/MembershipExtras/Upgrader/Steps/Step0011.php
xml/customFields_install.xml

Adding `payment_scheme_id` custom field to "Payment Plan extra attributes" custom group, so we can use it to link a recurring contribution to a payment scheme.
The initial plan was to create new entity with the following:
- 3 fields (id, contribution_recur_id, payment_scheme_id) 
- With API v3 and API v4 support to be able to do all the CRUD operations on this entity.
But I found that we already have a custom group called "Payment Plan extra attributes"  on the payment plan, so I found that it is easier and probably better to just add new field to it instead of creating new entity.
Also in general having API v3 support is not that important, and that we can just use API v4, which allows us to update or retrieve the value of this field using its name (unlike V3 that requires the custom …

CIWEMB-213: Add field to link recur contribution with payment scheme

---

CRM/MembershipExtras/Service/PaymentScheme/PaymentPlanScheduleGenerator.php
Civi/Api4/Action/PaymentScheme/GetPaymentSchemeSchedule.php
tests/phpunit/CRM/MembershipExtras/Service/PaymentScheme/PaymentPlanScheduleGeneratorTest.php

Creating new API v4 action `PaymentScheme`.`GetPaymentSchemeSchedule`, that generates the instalments schedule for a recurring contribution (payment plan) that is linked to a payment scheme, using the payment scheme instalments configurations.
This API will be used by payment processor extensions like GoCardless and Stripe to help creating `Payment Schedule` on such payment processors.
~
- New API  v4 action `PaymentScheme`.`GetPaymentSchemeSchedule` is now avaiable.
- That takes `contributionRecurId` as an input.
- And expect such recurring contribution to have a payment scheme to be linked to it (it throws an error if no payment scheme is linked to the input recurring contribution), where the payment scheme parameters field is expected to be configured by the admin in the following JSON …

CIWEMB-214: Create API to generate the payment plan schedule based on payment scheme

---

js/paymentPlanToggler.js

The same instance of the membership creation form can be submitted multiple times if the user clicks on the submit button more than once, which results in creating multiple memberships and contributions.:
here you can see how the "Save" button is still available during the form submission:
The same instance of the membership creation form can be submitted only once, which is achieved by disabling the form buttons after the user clicks on "Save":
here you can see how the "Save" button and the form buttons in general are now disabled during the form submission:
I am using two differenet selectors for the form buttons which are:
`.ui-dialog-buttonset button`
and
`.crm-submit-buttons button`
the first is the selector that get used when opening the membership creation form through the a modal, …

CIWEMB-260: Prevent membership creation form multi submission

---

CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItem.php
api/v3/ContributionRecurLineItem.php
js/CurrentPeriodLineItemHandler.js
templates/CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItem.tpl
tests/phpunit/CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItemTest.php
tests/phpunit/api/v3/ContributionRecurLineItemTest.php
xml/Menu/membershipextras.xml

Making the manage instalments screen more flexible, where the user can now add a membership line item, even when all the instalments within the payment plan are completed (pain).
Currently, the ability to add new membership line item (or even a normal line item) is not supported in Membershipextras when all the the instalments (contribution)  within the payment plan are completed (paid), and an error toast message is shown when the user tries to do so.
> (the error toast message appears in the background currently, but that is a separate and known UI problem)
Instead of showing the error toast message mentioned in the "before" section above, we now present two options to the user, the first is to create the membership without charging the user for it in the current period:
With this …

CIWEMB-264: Allow adding membership line item when there are no pending instalments left in the payment plan

---

CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsDonationLineItem.php
CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItem.php
api/v3/ContributionRecurLineItem.php
templates/CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsDonationLineItem.tpl
tests/phpunit/CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsDonationLineItemTest.php
xml/Menu/membershipextras.xml

Making the manage instalments screen more flexible, where the user can now add a line item, even when all the instalments within the payment plan are completed (paid).
This PR is the continuation to the work here: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/470
, where that PR is about adding membership line items, and this one is about adding standard non membership line items.
Currently, the ability to add new (non membership) line item is not supported in Membershipextras when all the the instalments (contribution)  within the payment plan are completed (paid), and an error toast message is shown when the user tries to do so.
Instead of showing the error toast message, we now show a confirmation message, allowing the user to create on off payment:
And as you can …

CIWEMB-267: Allow adding payment plan line item when there are no pending instalments

---

CRM/MembershipExtras/BAO/PaymentScheme.php
CRM/MembershipExtras/Form/PaymentScheme.php
templates/CRM/MembershipExtras/Form/PaymentScheme.tpl
templates/CRM/MembershipExtras/Page/PaymentScheme.tpl

This PR adds the ability to delete a payment scheme that has not been linked to any recurring contribution. 
Delete link did not work. 
_Screencast shows a payment scheme cannot be deleted if it has been linked to a recurring contribution(s). The error toast message will display if the payment scheme cannot be deleted._ 
[screencast to delete payment scheme.webm](https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/208713/27ac3a21-8944-44ff-a3be-97b0f3234ad9)
_Screencast shows payment scheme was deleted successfully._ 
[screencast-compucorp.atlassian.net-2023.06.06-14_31_21.webm](https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/208713/27770b1e-665e-4352-b82a-57e1802c68da)
In this PR, I updated the existing class `CRM_MembershipExtras_Form_PaymentScheme …

CIWEMB-102: Allow deleting a payment scheme. 

---

membershipextras.php

CiviCRM core has this  'Cancel Auto-Renewal' action that shows up for any membership linked to a recurring contribution (basically if the contribution_recur_id field on the membership is set), this option is not useful for Membershipextras given we have our own mechanism to control if the membership should autorenewal or not, which is using the manage instalments form, so here we are hiding this action
The 'Cancel Auto-Renewal' action appears in both membership tab on the contact page, and on the memberships search form:
The 'Cancel Auto-Renewal' is not hidden in both pages:

CIWEMB-359: Hide 'Cancel Auto-Renewal' membership action

---

templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl

This is how the "Manage instalments" form usually look like:
But on small screens and specially when trying to add Membership line item with long name, the form UI will become less friendly:
This PR improves that by making the manage instalments modal full screen by default. 
The "Manage instalments" screen open in full screen mode by default:
I couldn't find an easy way within Civi to make the modal full screen by default, given it is added using the `hook_civicrm_links` and managed by Civi, and non of the hook options seems to allow the possibility of achieving that.  So my solution was an within the modal page template itself, to add a JS code that simulates the click event on the modal "Toggle full screen" button:
by using this selector `.crm-dialog-titlebar-resize`, and to prevent it …

CIWEMB-258: Make manage instalments form full screen by default

---

CRM/MembershipExtras/Form/RecurringContribution/AddLineItem.php
CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
CRM/MembershipExtras/Service/PaymentPlanStatusCalculator.php

"Manage instalments" screen on payment plans with count of instalments = NULL (which we treat as if it = 1, which is annual payment plan) is not loading.
"Manage instalments"  does not load for payment plans with instalments count = NULL:
The manage instalments screen loads fine:
When the recurring contribution number of instalments field is NULL and you open the manage instalments page, 
the following error is thrown:
```
Brick\Math\Exception\NumberFormatException: "The given value "INF" does not represent a valid number."
#0 /var/www/default/htdocs/httpdocs/sites/all/modules/contrib/civicrm/vendor/brick/math/src/BigNumber.php(81): Brick\Math\BigNumber::Brick\Math\{closure}()
#1 /var/www/default/htdocs/httpdocs/sites/all/modules/contrib/civicrm/vendor/brick/money/src/Money.php(192): …
```

HCSASPRT-66: Fix Manage Instalments page issues when number of instalments is NULL

---

CRM/MembershipExtras/BAO/ContributionRecurLineItem.php
CRM/MembershipExtras/Form/RecurringContribution/SwitchMembershipType.php
CRM/MembershipExtras/Service/MembershipLineProRataCalculator.php
CRM/MembershipExtras/Service/MembershipTypeSwitcher.php
api/v3/ContributionRecurLineItem.php
templates/CRM/MembershipExtras/Form/RecurringContribution/SwitchMembershipType.tpl
tests/phpunit/CRM/MembershipExtras/Service/MembershipTypeSwitcherTest.php

In this PR I am implementing the 2nd option "One Off Payment" in the membership switching form that is implemented here:
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/476
The "Charge them a one off fee for this change" on the "Switch Membership" form does nothing.
When clicking on the mentioned option, a list of extra fields will appear to the user to allow them to enter the details for the "one off payment":
These fields are:
- `Scheduled Charge Date`: The default value is same as the "Switch Date" which is "Today Date + 1 day", but can be changed by the user and will be used as the new contribution date (receive_date).
- `Amount exc Tax`: Will be calculated automatically based on the following:
A: The current membership line type.
B: The new membership type that we …

CIWEMB-269: Simplify switching payment plan membership from one type to another - One off Payment

---

CRM/MembershipExtras/Form/PaymentScheme.php

This PR updates the edit payment scheme form to not allow users to change the payment processor for a scheme.
The user can edit the payment processor.
The user cannot edit the payment processor.
[CIWEMB-377-after.webm](https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/74309109/a6ade4e9-2a24-426e-9bb2-46bff46b66bc)
If the user is editing a payment scheme then we make the payment processor field disabled and not required.

CIWEMB-377: Don't allow changing the payment processor

---

.github/workflows/tests.yml
CRM/MembershipExtras/Hook/Config/APIWrapper/PaymentAPI.php
CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipEditTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculatorTest.php

The motivation for this PR is that when using the new SSP 'Switch to Direct Debit' button and choosing to pay any outstanding invoice with GoCardless, it results in extending the membership end date:
but I found that the problem is actually not limited to this option, but can also happen whenever the Payment.create API is used to pay for any pending contribution that is linked to a membership.
Using the Payment.create API on any pending invoice (contribution) that is linked to a payment plan membership does not result in extending the membership end date, this also includes using the SSP "Switch to Direct Debit" button and then selecting "Pay outstanding invoices" option.
GoCardless uses the Payment.create API when using the "Pay outstanding invoices" option after switching the payment …

CIWEMB-433: Prevent extending payment plan memberships when using Payment create API

---

CRM/MembershipExtras/Service/PaymentScheme/PaymentPlanScheduleGenerator.php
tests/phpunit/CRM/MembershipExtras/Service/PaymentScheme/PaymentPlanScheduleGeneratorTest.php

If for example you have a  payment scheme with the following configuration:
`{"instalments_count": 2,"instalments": [{"charge_date": "1 December"},{"charge_date": "1 December, + 1 month"}]}`
And then you:
1- Create an annual membership with the start date = 2nd August 2022, end date = 1st August 2023. 
2- Switch the recurring contribution (payment plan) to use Direct Debit with the above payment scheme.
3- Visit  the recurring contribution view page and you will see the following in the “Future payment scheme Instalments”:
which is all correct given the payment scheme configurations.
4- Run the autorenewal scheduled job (assuming today's date is >= 1st August 2023 or you are using autorenewal in advance setting to renew in advance), two contributions with the dates shown in the “Future …

CIWEMB-438: Introduce {next_period_year} payment scheme token to allow better configurations

---

CRM/MembershipExtras/Hook/PageRun/ContributionRecurViewPage.php

The "Future payment schedule" in the recurring contibution shows dates in "Y-m-d" format.
These dates now show in CiviCRM complete date format:

CIWEMB-439: Respect civicrm default date format when showing future payment schedule

---

CRM/MembershipExtras/Form/RecurringContribution/Cancel.php
CRM/MembershipExtras/Hook/Links/RecurringContribution.php
templates/CRM/MembershipExtras/Form/RecurringContribution/Cancel.tpl

With the work in this PR: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/462 we now support payment processor extensions to opt in for Membershipextras support, extensions like GoCardless (and Stripe in the future) are examples of such payment processors that will opt for Membershipextras support.
At the moment when the user tries to cancel a recurring contribution, where the recurring contribution uses a payment processor that opted for Membershipextras support, the following screen will appear:
which as you can see allow users to decide if they also want to cancel any linked pending instalment (contribution) and/or linked memberships. But with payment processors like GoCardless, it would be important to sync the cancelation on CiviCRM with GoCardless (a one way sync, …

CIWEMB-347: Support for payment cancellation workflow for external (non offline) payment processors

---

CRM/MembershipExtras/Hook/PageRun/ContributionRecurViewPage.php

"Future payment scheme schedule" shows for both active and non active payment plans, but it make no sense for it to appear on non active payments given they are no longer in use, so there is not "future schedule" for them.
The "Future payment scheme schedule" no longer appears for inactive payment plans:

CIWEMB-438: Show future payment schedule for active payment plans only

---

CRM/MembershipExtras/Hook/PageRun/ContributionTab.php
membershipextras.php
templates/CRM/Contribute/Page/Tab.extra.tpl

In this previous PR: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/473 I improved the recurring contribution view page for recurring contributions that uses payment schemes, so they no longer show unnecessary information such as the "Frequency" and the "Cycle Day", though on the recurring contribution tab the "Frequency" tab still shows the frequency information for such recurring contributions.
For any recurring contribution linked to a payment scheme, I now replace the frequency information with the following: `~ Payment Scheme ~` to indicate that this recurring contribution uses a payment scheme.
The recurring contribution tab is part of the contribution tab and loads with it, so I: 
1- Implemented the `pageRun` hook on the contribution tab.
2 - And from the …

CIWEMB-389: Reword the frequency column for payment scheme recurring contributions

---

CRM/MembershipExtras/Hook/ValidateForm/UpdateSubscription.php

1- Recurring an annual recurring contribution.
2- Use SSP to switch it to use GoCardless Direct debit payment processor.
3- Go to the recurring contribution tab on Civi and try to edit the recurring contribution above.
4- try to click on “Submit” and the form will keep loading indefinitely. 
Payment scheme recurring contribution can be edited normally:
We use this API end point in the Automateddirectdebit extension:  https://github.com/compucorp/io.compuco.automateddirectdebit/blob/8e2c6699c8eddaa5021cda9c2ad320a54ba9fbc6/Civi/Api4/Action/AutoDirectDebitPaymentPlan/SwitchToDirectDebitPaymentScheme.php#L60 to switch the recurring contribution from annual to the selected payment scheme, and as part of that we set several unnecessary fields to NULL including the `frequency_interval` field: …

CIWEMB-452: Fix editing payment scheme recurring contributions

---

CRM/MembershipExtras/Hook/PageRun/ContributionTab.php
membershipextras.php
templates/CRM/Member/Page/RecurringContributions.extra.tpl

A follow up for this PR: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/492, where there I update the frequency column for recurring contributions that are linked to payment scheme under the recurring contributions tab, here I update the frequency column for such recurring contribution under the membership view as well.

CIWEMB-389: Reword the frequency column under membership view page for payment scheme recurring contributions

---

templates/CRM/MembershipExtras/Form/RecurringContribution/AddDonationLineItem.tpl
templates/CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.tpl
templates/CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsDonationLineItem.tpl
templates/CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItem.tpl
templates/CRM/MembershipExtras/Form/RecurringContribution/SwitchMembershipType.tpl

When trying to add a line item through the manage instalments screen, and after clicking "Apply", the "Apply" button will remain enabled until the form is fully submitted, which might lead to users clicking on it twice or more by mistake, which may result in multiple submissions. 
When trying to add a line item through the manage instalments screen or if you are using the "Switch membership type" option, and if you select a "one-off payment" option and entered a non numeric value, then the payment form will disappear and nothing will happen:
The "Apply" button will be disabled after the user clicks on, and so preventing multi submissions:
Entering non numeric value in the amount field will show the validation error properly.

CIWEMB-476: Usability improvements to the "manage instalments" forms

---

CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsDonationLineItem.php
CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItem.php

This updates the some of the notification messages that appear when we add line items through the manage instalments form, so they match the ones mentioned in our specs document on Confluence, these messages are:
- When adding membership line item and selecting "No Payment" option, then it should show: 
`The membership has been added to payment plan but no payment has been created.`
- When adding membership line item and selecting "On-off Payment" option, then it should show: 
`The membership has been added to payment plan and a payment has been created successfully`
- When adding membership line item and an error occur then  it should:
`The membership could not be added to the payment plan. Error reason: ERROR_REASON_GOES_HERE`
- When adding a non membership line item then it should …

CIWEMB-475: Update manage instalment screen notification messages

---

js/CurrentPeriodLineItemHandler.js

If you are on the membership switching form, and then decided to close the form (modal) without changing anything, the manage instalment screen will be stuck showing a loading screen:
Closing the membership switching no longer blocks the manage instalments screen:

CIWEMB-488: Make the manage instalments form usable if the user cancels membership switching

---

templates/CRM/MembershipExtras/Page/EditContributionRecurLineItems.tpl

When doing some actions on the manage  instalments form, such as switching the membership type, the user will have to refresh the whole contact page manually to able to see the update contribution(s) and membership(s):
The Memberships and the Contributions tabs are now refreshed automatically when the user closes the manage instalments form:

CIWEMB-510: Refresh the contribution and the membership tabs when closing the manage instalments form

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php
CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItem.php

When the statuses "Current Renewed" and "Future Start" are disabled, if you try to add a membership line item with future date the following error will appear:
Which as you can see is not that great and shows the dates in not very readable format.
The error message that appear after trying to add a membership line with future date is improved:
In the manage instalment screen we catch exceptions that comes from Civi core and show it in the error notification as is, which is fine most of the time given most of the messages are readable, but given it is not the case with the status calculation message, I here search the exception message to check if it is really the status calculation message, and if so I replace its content with the improved wording.

CIWEMB-491: Replace the membership status calculation error message with more readable content

---

CRM/MembershipExtras/Form/PaymentPlanSettings.php
settings/PaymentPlan.setting.php

The "days to renew in advance" field is a text field that accepts any alphanumeric string where it should only accepts integers: 
The "days to renew in advance" field only accepts integers:
The 2nd commit in this PR allow adding extra attributes to setting fields, which is needed for this: https://github.com/compucorp/io.compuco.automateddirectdebit/pull/14 to work.

CIWEMB-490: Make the 'days to renew in advance' field accepts integers only

---

CRM/MembershipExtras/Form/RecurringContribution/AddNoInstalmentsMembershipLineItem.php
CRM/MembershipExtras/Form/RecurringContribution/RemoveLineItems.php
CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculator.php
tests/phpunit/api/v3/PaymentSchedule/GetPaymentScheduleTest.php

If you delete a membership line using the "manage instalments" form and that membership is linked to a one-off payment, then:
- The membership line will be removed from the payment plan
- The Membership end date will be altered so it = "Today's date" or to the date set by the user.
- But the but the one-off payment (contribution) will remain.
This behavior is not great given the user might assume that the one-off payment (contribution) will be automatically removed, But contributions are "invoices" and they have a sequential number, so we cannot just remove them either.
So to make things a bit better for the user, we have two possible options:
1- Issue a credit note for the one-off payment.
2- Prevent the user from removing the membership line if it is linked to a one-off payment, and if …

CIWEMB-487: Prevent deletion membership lines linked to one-off payments

---

CRM/MembershipExtras/BAO/PaymentScheme.php
CRM/MembershipExtras/Form/RecurringContribution/Cancel.php
CRM/MembershipExtras/Hook/PageRun/ContributionRecurViewPage.php
CRM/MembershipExtras/Hook/PageRun/ContributionTab.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentSchemePlan.php

In  these PRs:
- https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/473
- https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/496
I did updates to the Recurring contribution view page and tab, where it now indicates if the recurring contribution is linked to a payment scheme and hide any unnecessary information.
But we found out that the work above does not work for users with only 'CiviCRM User' role, or users in general with limited permissions.
The work done in the above PRs work fine for users with 'CiviCRM User' role or users who have enough permission to access the recurring contribution tab in general:
Some of the API calls in the backend code are using API v4, which by default enforce permission checks, but most of the time API calls that are done …

CIWEMB-389: Fix payment scheme UI support for non admin users

---

CRM/MembershipExtras/Form/RecurringContribution/SwitchMembershipType.php

A follow up for this PR: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/502 where I also update the membership status calculation error with something more readable when switching the membership from one type to another.
https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/6275540/382fa5dd-55fc-45e4-af0d-f4456093ba70
https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/6275540/6a4c1531-14d1-4c89-9f8b-c5abde0451aa

CIWEMB-491: Replace the membership status calculation error with more readable content when switching membership type

---

CRM/MembershipExtras/Form/PaymentScheme.php

This pr corrects the labels for fields to display the error message correctly.

CIWEMB-373: Correct field labels for error display

---

CRM/MembershipExtras/Service/MembershipLineProRataCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/AbstractPeriodTypeCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculator.php
CRM/MembershipExtras/Service/MembershipTypeDurationCalculator.php
CRM/MembershipExtras/Service/MembershipTypeSwitcher.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculatorTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipTypeSwitcherTest.php
tests/phpunit/api/v3/PaymentSchedule/GetPaymentScheduleTest.php

If you have a fixed membership with:
- Fixed Period Start Day = 1st of Jan
- Fixed Period Rollover Day = 31th of Dec
- Annual Pro-rata Calculation = By Days
And you are trying to create a fixed membership with payment plan in non leap year (such as 2023), but with future dates that fall within a leap year (such as 2024-01-01 to 2024-12-31), then the membership form will keep not allow you to set the end date to "2024-12-31", and instead will keep changing the end date into  "2023-12-31" which is the fixed period rollover day during the current year (instead of the using the future year that you are trying to create the membership in), This will also result in showing wrong pro-rata membership fees:
https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/6275540/4b77faef-ffca-4 …

ESEB-115: Fix pro-rata calculation during leap years

---

CRM/MembershipExtras/Service/PaymentPlanNextContributionDate.php
CRM/MembershipExtras/WebformAPI/PaymentPlanNextContributionDateUpdater.php

If you configure a webform with a payment plan and a fixed 1 year membership that starts at 1st of January and ends at 31th of December:
then the created recurring contribution "Next Scheduled Contribution Date" will be:
- The first instalment receive date + 1 year (in case of single instalment payment plans)
Or
- The last instalment receive date + 1 month (in case of monthly payment plan).
This shouldn't be the case, and instead the "Next Scheduled Contribution Date"  should be:
- The membership end date + 1 day
The "Next Scheduled Contribution Date" is :  The membership end date + 1 day
The `PaymentPlanNextContributionDateUpdater` Webform API passes the word "Creation" as 2nd argument to the `PaymentPlanNextContributionDate` Service that is responsible for calculating the  "Next …

ESEB-137: Fix 'Next Contribution Date' for webform fixed memberships

---

CRM/MembershipExtras/Setup/Manage/ManualPaymentProcessor.php
CRM/MembershipExtras/Setup/Manage/ManualPaymentProcessorType.php
CRM/MembershipExtras/Setup/Manage/OfflineRecurringPaymentMethod.php

This PR fixes the extension installation on some sites.
Previously the extension installation was failing if the **EFT** payment method was not there as the creation of manual payment processor was dependent on **EFT** payment method.
This PR changes the flow to first create a new payment by the name of **Offline Automated Recurring** method that manual payment processor will use instead of **EFT**
We create a new payment method attached to default financial account of type **Asset** or the first financial account of type **Asset** if default financial account of type **Asset** is not present

MAE-1114: Fix The Extension Installation on some sites

---

CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
CRM/MembershipExtras/Hook/ValidateForm/UpdateSubscription.php
templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl

In this PR: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/473
we hid several fields from the recurring contribution view page if it is linked to a payment scheme,  here we are doing the same on the recurring contribution edit form.
The recurring contribution "edit" form shows the following fields:
and when trying to submit the form it shows the following message:
These fields are now hidden:
- Frequency
- Instalments
- Cycle Day
- Next Scheduled instalment
and when trying to submit the form, it no longer mentions the "Cycle day", but rather it shows the same message that appear to "annual" payment plans:
where recurring contributions that are not linked to a payment scheme still work as they used to where all these fields are visible:
The "Cycle day" and "Next …

CIWEMB-535: Hide fields that are unnecessary for payment plans linked to payment schemes

---

CRM/MembershipExtras/API/PaymentSchedule/Base.php
CRM/MembershipExtras/API/PaymentSchedule/PriceValues.php
CRM/MembershipExtras/Hook/CustomDispatch/CalculateMembershipMinimumFee.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/AbstractProcessor.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Page/InstalmentSchedule.php
CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
js/paymentPlanToggler.js
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItemTest.php

This pull request introduces a hook/event, `me.membership.calculate_minimum_fee`, enabling third-party extensions to modify the minimum fee associated with a membership type during the following operations:
- Instalment table generation
- Computation of membership contribution instalment amounts
- Membership offline auto-renewal job execution
Additionally, an exception is now appropriately thrown when attempting to generate an instalment table for a Price field lacking a membership type.

BTHAB-293: Allow extension to update membership minimum

---

CRM/MembershipExtras/Form/RecurringContribution/SwitchMembershipType.php

When trying to switch a membership from one type to another, the current membership type still appears in the list of membership types that you can switch to:
https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/6275540/1ed45c12-0164-440f-a1e3-44434d5bf81c
The current membership type no longer appears in the list of membership types that you can switch to:
https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/6275540/1e614a7b-5cb1-4cfa-9f83-e7d6dbbbdff9
The "New membership type" field is an a civicrm entity reference field which is added by calling `$this->addEntityRef()` in the buildForm method (see: https://docs.civicrm.org/dev/en/latest/framework/quickform/entityref/) ,  so all I need is to add an API parameter to `$this->addEntityRef()` to exclude the …

 CIWEMB-492: Prevent switching to the same membership type

---

CRM/MembershipExtras/Hook/PageRun/ContributionRecurViewPage.php
js/modifyRecurringContributionPage.js

In this PR: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/473 we hide various fields that are irrelevant for payment plans that are linked to payment schemes, but this was only done for active payment plans, so it would be better if we also hide them for non active payment plans as well.
The following fields appear on inactive payment plans that are linked to payment schemes:
- Frequency
- Installments
- Cycle Day
- Next Scheduled Contribution Date
https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/6275540/2e2f3f49-4edc-473a-91a8-14794b17e4a2
The mentioned fields no longer appear on inactive payment plans that are linked to payment schemes:
https://github.com/compucorp/uk.co.compucorp.membershipextras/assets/6275540/7736fd4d-fe9c-426b-981a-5543666a70b …

COMCL-410: Hide unnecessary fields for non active payment plans that are linked to a payment scheme 

---

membershipextras.php

This pr makes 'view' option visible for memberships on contact view page.
The issue was introduced in this [pr](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/474) where we wanted to hide 'Cancel Auto-Renewal' option for memberships linked to a recurring contribution, but if this option is not available for any membership then array_search [here](https://github.com/compucorp/uk.co.compucorp.membershipextras/blob/master/membershipextras.php#L386) returns false and as a result [this](https://github.com/compucorp/uk.co.compucorp.membershipextras/blob/master/membershipextras.php#L387) line unsets the first item in links array.

ESESPRT-77: Show View Option For Memberships

---

templates/CRM/MembershipExtras/Form/RecurringContribution/SwitchMembershipType.tpl

This pr improves the ui of "change membership type" screen by bringing the current and new membership sections closer to each other.

CIWEMB-509: Make Current and New Membership Sections Closer

---

CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/AbstractProcessor.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/Contribution.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItem.php
CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculator.php
CRM/MembershipExtras/Service/MembershipPeriodType/PeriodTypeCalculatorInterface.php
CRM/MembershipExtras/Service/MembershipPeriodType/RollingPeriodTypeCalculator.php
membershipextras.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItemTest.php

This pr fixes an issue with pro rata calculation of membership payment plan that caused pro rata to be applied twice to the same amount resulting in significant less amount being charged for membership.
When quick config price set was used for creating a membership pro rata calculation was applied [here](https://github.com/compucorp/uk.co.compucorp.membershipextras/blob/6b1bdadaa43ce727f44932f65e49529620bd2c88/CRM/MembershipExtras/Service/MembershipPeriodType/FixedPeriodTypeCalculator.php#L83) to already prorated amount so this pr fixes this issue.

FOSFASPRT-9: Fix pro rata calculation for membership payment plan

---

js/paymentPlanToggler.js

This pr fixes date field issue on memberhsip form.

COMCL-680: Fix Membership Form Date Field Issue

---

css/membershipView.css
membershipextras.php

This pr fixes the styling for membership view screen as currently 'Related Contributions and Recurring Contributions' section is not visible properly.

COMCL-765: Fix Styling For Membership View Page

---

CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItem.php

Before this PR we had an issue where when a user ‘record’ a payment against a membership contribution with total computed from [membersjhiprate](https://github.com/compucorp/io.compuco.membershiprates) extension, the amount due is shown as the amount attached to the original membership type ‘minimum fee’ (ie, pre calculation from the membership fee calculator).
The event we added here https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/508, requires that contactID be sent, but in the line item create hook, the contact ID was null.
In this PR we have retrieved the set the contact ID from the line item contribution.
The amount due is shown as the amount attached to the original membership type ‘minimum fee.
The amount due is shown as the amount calculated by the membership …

BTHA-194: Ensure membeership rate total can be calculated for line item

---

CRM/MembershipExtras/Service/MembershipPaymentPlanActivation.php

Currently during membership renewal if user tries ti switch payment method or payment plan, user receives an error. This pr fixes this issue

COMCL-822: Fix Membership Renewal

---

CRM/MembershipExtras/Service/MembershipInstalmentsSchedule.php
js/paymentPlanToggler.js

Currently when user is creating a membership on a contact. The “member since” field is pre-populated to today’s date and the price in the contribution tab is populated to the full price for the membership, if the user adjusts the date (in the example to future date the membership), the price remains at the full price for the year and if the user then submits with no other changes, the pro-rating of the membership price has effectively not occurred. So this pr fixes the issue now whenever user selects a membership or price set or adjusts the mebership start date the total amount adjusts automatically to pro rata amount.

MAE-1178: Fix Pro Rata Calculation For Membership

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlan.php

Before this PR membership with paid contributions did not get renewed, this is because of a recurring contribution condition that filters out recurring contributions with non-empty end date
Membership did not get renewed, and no new contribution was created after running the renewal job
Running the renewal job now renews the membership with a completed contribution and creates a new pending contribution
This issue didn't happen in the previous CiviCRM version because completing a contribution does not change the end date of the recurring contribution.

COMCL-887: Support renewal of paid contribution

---

CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/LineItem.php

Before this PR we had an issue where when a user ‘record’ a payment against a membership contribution with total computed from [membersjhiprate](https://github.com/compucorp/io.compuco.membershiprates) extension, the amount due is shown as the amount attached to the original membership type ‘minimum fee’ (ie, pre calculation from the membership fee calculator).
The event we added here https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/508, requires that contactID be sent, but in the line item create hook, the contact ID was null.
In this PR we have retrieved the set the contact ID from the line item contribution.
The amount due is shown as the amount attached to the original membership type ‘minimum fee.
The amount due is shown as the amount calculated by the membership …

BTHA-194: Ensure membership rate total can be calculated for line item

---

templates/CRM/MembershipExtras/Page/InstalmentSchedule.tpl

Avoid reformatting total amount in the template, this regression was introduced in this PR https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/539, where we formatted the total amount from the Backend to a string, while the frontend view also attempts to format the same total amount with the expectation that the value is float.
The total amount value is empty
The total amount value is no longer empty

COMCL-939: Avoid reformatting total amount in the template

---

CRM/MembershipExtras/Service/FinancialTransactionManager.php
tests/phpunit/CRM/MembershipExtras/Service/FinancialTransactionManagerTest.php

Currently for additional line item creation the transaction record does not include VAT if the line item financial type is configured for VAT.
Additional line item can be added by going to a contact record with an active recurring contribution and selecting View/Modify Future Instalments from more options for the recurring contribution and then on the modal adding anew donation item or membership item.
Vat was not included in total amount of the transaction record for additional line item
Vat is now included in total amount of the transaction record for additional line item

CIWEMSPRT-50: Fix Financial Transaction Record For Additional Line Item Creation

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php
templates/CRM/MembershipExtras/Form/RecurringContribution/Cancel.tpl

This PR fixes a bug which restricted a user from cancelling a recurring contribution. Previously when user cancelled a recurring contribution the status did not change.

CIVIPLMMSR-480: Fix Cancellation Of Recurring Contribution

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstalmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentSchemePlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlan.php
CRM/MembershipExtras/Setup/Manage/OfflineAutoRenewalScheduledJob.php
CRM/MembershipExtras/Upgrader/Steps/Step0013.php
api/v3/OfflineAutoRenewalJob.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/MultiInstalmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipTypeSwitcherTest.php

This update refactors the offline auto-renewal job to better handle **single instalment** and **multiple instalment** membership renewals. Each renewal type now runs through a dedicated scheduled job and processing queue, improving isolation and scalability.
The job `Renew offline auto-renewal membership` exists as one
The job `Renew offline auto-renewal membership`  is separated into two `Renew offline multiple instalments auto-renewal memberships (Daily)` and `Renew offline single instalment auto-renewal memberships (Daily)`
* **Split job logic**
* Introduced `runSingle()` and `runMultiple()` methods in `OfflineAutoRenewal`.
* `SingleInstalmentPlan` and `MultipleInstalmentPlan` classes now have distinct queue names for task separation.
* **Queue-based processing**
* Moved renewal …

CIWEMB-619: Run Membership renewal job in a queue
