CRM/MembershipExtra/Hook/PreEdit/Membership.php
CRM/MembershipExtra/PaymentProcessor/OfflineRecurringContribution.php
CRM/MembershipExtra/PaymentProcessorType/ManualRecurringPayment.php
CRM/MembershipExtra/Upgrader.php
CRM/MembershipExtra/Upgrader/Base.php
Drupal/civicrm_membershipextra/civicrm_membershipextra.info
Drupal/civicrm_membershipextra/civicrm_membershipextra.module
Drupal/civicrm_paymentplan/civicrm_paymentplan.info
LICENSE.txt
info.xml
membershipextra.civix.php
membershipextra.php
readme.md

As requested by guahnaun/jamie, I changed the extension name  from **uk.co.compucorp.paymentplan** to **uk.co.compucorp.membershipextra**

BASW-42: Renaming the extension from paymentplan to membershipextra

---

CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php

When paying for a membership offline using "contribution" option and setting the membership to auto-renew automaticly : 
then running the offline auto-renewal scheduled job (given that the membership end date is in the past) won't extended the membership nor create a new pending contribution.
This is because when paying using contribution option, the  contribution 'contribution_recur_id' was not getting updated too to point to the auto-renewal recurring contribution.
I updated the code that post Process membership form when using offline auto-renewal to set the  'contribution_recur_id' for the last membership contribution to point to the auto-renewal recurring contribution :

BASW-68: Fix autorenewal for membership offline contribution payments

---

CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor.php
CRM/MembershipExtras/Job/OfflineAutoRenewal.php

This fixes amounts and taxes calculations so they all rounded to the nearest penny/cent instead of not rounding the result at all.

BASW-81: Fixing amounts and taxes calculation

---

CRM/MembershipExtras/Job/OfflineAutoRenewal.php

When the offline memberships auto-renewal scheduled job run, the new created recurring contribution will always the payment method = EFT even if the previous recurring contribution has a different payment method.
The new recurring contribution will use the same payment method used in the previous recurring contribution.

BASW-68: Ensure that the correct payment method is used when auto renewing offline memberships

---

CRM/MembershipExtras/PaymentProcessor/OfflineRecurringContribution.php
CRM/MembershipExtras/PaymentProcessorType/ManualRecurringPayment.php
CRM/MembershipExtras/Upgrader.php

This PR ensures that : 
1- All the important payment processor and payment processor type info are provided during the creation such as the financial type account, user name label and placeholder URLs.
2- Both Live and Test version of the payment processor are created, disabled, enabled and removed correctly.
I also a bit of refactoring to the OfflineRecurringContribution class

BASW-169: Ensure that all the important payment processor and payment processor type data are added correctly

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php

When all the instalment contributions are marked as completed (a full payment is recorded), the recurring contribution is marked as completed too. The recurring contribution end date should also be set to the cycle day of the last interval.
Also, if the number of instalments is equal to or smaller than 1, the recurring contribution should neither be marked as completed nor having the end date set.
Although the recurring contribution status was being set as Completed when all instalments were payed, the end date was not being set.
End date for the recurring contribution is set when all payments have been completed, and this end date is now used to set the end dates of recurring line items associated to it.

BASW-122: Set Recurring Contribution End Date

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php

When all the instalment contributions are marked as completed (a full payment is recorded), the recurring contribution is marked as completed too. The recurring contribution end date should also be set.
Also, if the number of instalments is equal to or smaller than 1, the recurring contribution should neither be marked as completed nor have the end date set.
This fix was already done on phase 3 workstream on PR #88 , but needs to be sent to alpha-release to be deployed immediately existing installations. 
Although the recurring contribution status was being set as Completed when all installments were paid, the end date was not being set.
End date for the recurring contribution is set when all payments have been completed.

BASW-122: Set Payment Plan End Date On Completion

---

CRM/MembershipExtras/Hook/Post/EntityFinancialTrxn.php
CRM/MembershipExtras/PaymentProcessor/OfflineRecurringContribution.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.tpl
templates/CRM/MembershipExtras/Form/RecurringContribution/Cancel.tpl

We needed to bring into Phase 3 workstream all the fixes done on develop branch, but some conflicts required the merge to be done locally and bring them in using a new PR.

Update phase 3 workstream with develop

---

CRM/MembershipExtras/Upgrader.php
js/CurrentPeriodLineItemHandler.js
js/NextPeriodLineItemHandler.js

1. When an user adds/ removes a line from the current period, a "Update Payment Plan Current Period" type activity should be generated with:
a. Subject - "Update Payment Plan Current Period"
b. Source Record ID - ID of the recurring contribution
c. Added by - Admin
d. With - The contact of the recurring contribution
2. When an user adds/ removes a line from the next period, a "Update Payment Plan Next Period" type activity should be generated with:
a. Subject - "Update Payment Plan Next Period"
b. Source Record ID - ID of the recurring contribution
c. Added by - Admin
d. With - The contact of the recurring contribution
Action did not exist
Action has been implemented

BASW-288: Record an Activity When Change is Made Installment Management Screen

---

CRM/MembershipExtras/Hook/Pre/ContributionRecur.php

When the full number of instalment contributions are marked as completed, the recurring contribution need to be marked as completed too. The recurring contribution end date should also be set to the cycle day of the last interval.
On completion of payment plan, end date was being set as actual date, instead of receive date of last installment of the payment plan.
The recurring contribution end date is now set to the receive date of the last installment.

BASW-122: Fix Recurring Contribution End Date Calculation on Completion

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php

Adding a line item to current period, when it was already on next period, was duplicating a subscription line, and overwriting line items from other contributions.
When obtaining the list of line items to see if membership type already existed on next period, the returned 'id' was being used as the ID of the line item. However, this ID corresponded to the recurring subscription line.
Used 'line_item_id' to update existing line item, and 'id' to update subscription line, if an existing line is found for the same membership type.

BASW-219: Fix Bug Causing Line Items to Be Duplicated and Overwritten

---

CRM/MembershipExtras/Upgrader.php

QA reported the error below after running the upgrader.
```
[Error: Upgrade uk.co.compucorp.membershipextras to revision 0001]
CiviCRM_API3_Exception: "Mandatory key(s) missing from params array: custom_group_id".
```
Upgrader failed because of this line
https://github.com/compucorp/uk.co.compucorp.membershipextras/blob/5e2958c95d67b7259d19e10a9a37beb49ddc319c/CRM/MembershipExtras/Upgrader.php#L236
and this line
https://github.com/compucorp/uk.co.compucorp.membershipextras/blob/5e2958c95d67b7259d19e10a9a37beb49ddc319c/CRM/MembershipExtras/Upgrader.php#L236
Changing them to `'custom_group_id' => 'related_payment_plan_periods',` solves the problem but another is found. 
The upgrade runs infinitely creating infinite subscriptions line items. 
`getLastInstalmentForPaymentPlan()` does not …

BASW-259: Fix bug causing subcription lines to be created infinitely

---

templates/CRM/Member/Form/PaymentPlanToggler.tpl

This PR transforms “Contribution and Payment Plan” radio buttons into a tab navigation bar.
Important! Please note that the BASW-377 will fix the paddings around the table.
At first, we add a navigation bar with tabs:
```html
<div id="payment_plan_fields_tabs">
<input name="contribution_type_toggle" type="hidden">
<div class="ui-tabs">
<ul class="ui-tabs-nav ui-helper-clearfix">
<li class="crm-tab-button ui-corner-top ui-tabs-active" data-selector="contribution">
<a href="#contribution-subtab">Contribution</a>
<li class="crm-tab-button ui-corner-top" data-selector="payment_plan">
<a href="#payment_plan-subtab">Payment Plan</a>
```
Please note, we change radio buttons to input type hidden. We still need a form element because it gets submitted to the PHP script.
We have a function that …

BASW-375: Refactor the Payment Plan toggler

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php
CRM/MembershipExtras/Hook/PostProcess/UpdateSubscription.php
CRM/MembershipExtras/Hook/PreProcess/ContributionView.php
js/CurrentPeriodLineItemHandler.js
membershipextras.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl
templates/CRM/MembershipExtras/Page/NextPeriodTab.tpl

Some issues were detected while testing addition of line items to current period:
- Once line item is added successfully the pending contributions are adjusted with the new amount, but the line items in the individual contributions are not displayed.
- Able to add line item with End Date which is less than Start Date.
- For a recurring contribution with auto-renew set as 'False' already, added a new membership line item via Manage Installments popup. But newly added membership line item is displayed with Auto-Renew check selected in Membership Tab.
- Tax field is not showing N/A, if there is no tax account in the financial type selected. Also Amount text box is displayed as 'NaN'.
- Line items not shown on Contribution view: This is due to CiviCRM bug/feature documented in …

BASW-220: Fix Issues Adding Memberships to Current Period

---

CRM/MembershipExtras/Hook/Pre/MembershipCreate.php

- Adding a membership (with pending payment) with type similar to an existing membership
- Edit the pending contribution and set the status to complete then save.
- The page will hang and when you refresh it an error saying that the membership join date should no be larger than the first active period end date will appear.
No error is appearing anymore and the periods as well as the membership dates are updated correctly
Before this PR, adding a pending membership with similar type as an existing one will change the membership status to "Pending". and completing a contribution using "Edit" button instead of "record payment"  takes a different path that will result in setting the join date of the membership to today date if the current membership status is "Pending", and because in our …

RSE-63: Fix an error when adding a pending membership with type similar to existing one

---

CRM/MembershipExtras/Form/RecurringContribution/AddMembershipLineItem.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

Reverts compucorp/uk.co.compucorp.membershipextras#192

Revert "BASW-289: Do not save end date for lifetime memberships."

---

info.xml

We need to update info.xml to tag first stable release of membership extras extension.

CGP-1450: Tag Stable Release

---

CRM/MembershipExtras/Upgrader.php

Cycle days of existing payment plans were wrong, as per the plan's start date. Most yearly 1 installment payment plans had a cycle day of 1, causing, on renewal, the recieve date to be set for the first of january, even if the other contributions in the plan were set for different dates.
Payment plans created on previous versions of membership extras had cycle dates set according to rules that differ from those implemented currently.
Added functionality to upgrader to recalculate cycle day.

CGP-1450: Recalculate Cycle Day of Existing Plans on Upgrade

---

info.xml

Updating info.xml file to match state of release:
- Changed development stage to 'stable'
- Changed compatibility version to 5.13.5

CGP-1450: Update info.xml for Release of v1.0-stable

---

CRM/MembershipExtras/Form/RecurringContribution/RemoveLineItems.php

On some payment plans, after removing membership line item/contribution line item from 'Manage Installments', it was not updating the contribution amount & membership tab.
For payment plans created in the past (say for a membership from 2000-01-01 to 2000-12-31), with pending installments, if a line item was removed and the end date not adjusted, end date was being set as the current date. When removing line itmes from pending contributions, the system was only removing them for pending contributions AFTER the end date.
Implemented a validation on selected/default end date, such if there are no pending installments found after the end date, an exception is thrown to alert the user.

MAE-168: Fix Removal of Recurring Line Items for Past Contributions

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

Period start and end date that was shown on manage installments pop-up was taken from the recurring contribution. However these values are used internally to manage auto-renewals, in such a way that periods that have not been renewed do not have an end date, until they completely paid for. Also, plans with single installment never have an end date, despite the related memberships do. All this can cause confusion to the user.
Thus, we need to change the logic that shows period start and end dates (for both current and next periods), so that these are calculated on the fly when viewing the Manage Installments page.
- Current period start and end dates came from the recurring contribution.
- Next period start date was calculated by checking the recieve date of the last installment, and …

MAE-155: Change How Period Start and End Dates are Calculated

---

CRM/MembershipExtras/Hook/PreSave/Membership.php
membershipextras.php

This PR is based on the new hook added in this Core PR : https://github.com/civicrm/civicrm-core/pull/12253 which is not yet reviewed/merged.

BASW-123: Prevent Membership cancellation on payment plan cancellation

---

CRM/MembershipExtras/Hook/PostProcess/RecurringContributionLineItemCreator.php
CRM/MembershipExtras/WebformAPI/RecurringContributionLineItemCreator.php
CRM/MembershipExtras/WebformAPI/UpfrontContributionsCreator.php

Please check https://github.com/compucorp/webform_civicrm_membership_extras/pull/12 for more details

MAE-175: Ensure that the auto-renew flag is set correctly after webform submission

---

CRM/MembershipExtras/Hook/Pre/MembershipEdit.php

Trying to record a payment related to a membership in a new tab or using the record payment option inside "edit contribution" form will result in extending the membership end date for payment plan membership for every payment (or installment) get paid. The end date should only be extended during renewal and not for every installment we pay.
Completing payment plan installments  in a new tab is not affecting the related membership end date anymore 
The membership edit hook implementation was relying on the existence of certain query parameters to detect if the membership is being edited as a result of recording a payment related to it, these parameters are : 
- action
- component
- id
- _qf_AdditionalPayment_upload
Though and while these parameters (excpet _qf_AdditionalPayment_upload …

CGP-1487: Fix membership end date when recording payment from different screens

---

CRM/MembershipExtras/Upgrader.php

Offline Auto-renewal scheduled job fails when "days to renew in advance" setting is set and shows the following error in the logs : 
`Finished execution of Renew offline auto-renewal memberships with result: Failure, Error message: Errors found on auto-renewals: An error occurred renewing a payment plan with id (3): The membership cannot be saved because the status cannot be calculated for start_date: XXXXX end_date XXXXX  join_date XXXXX  as at XXXXX`
Offline Auto-renewal scheduled job works normally as it used to.
The issue is caused by two other PRs : 
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/225
and 
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/223
The first PR changed the offline auto-renewal so the membership start date is updated to …

MAE-183: Fix autorenewal when 'date in advance' setting is set

---

CRM/MembershipExtras/Hook/Post/MembershipPayment.php
CRM/MembershipExtras/Hook/Pre/MembershipEdit.php

When renewing payment plans memberships with more than one installment manually (from the renew action inside the membership tab/ contact page), the end date of the membership will get extended once, then it will get extended again for every installment in the payment plan, for example if you create a membership with the following dates assuming that today date = (21/1/2020): 
Start date = 21/1/2020
End date = 20/1/2021 (1 year membership)
and completed the two installments, then renewed the membership again with a two installments pending payment plan from the "renew" action inside the membership tab, then the membership end date will become = 20/1/2024
Renewing memberships as part of multi installments membership will only extend the membership once, so in the case above the membership …

MAE-171: Prevent extending the membership multiple times on manual renewal

---

CRM/MembershipExtras/Hook/Post/MembershipPayment.php

When creating a membership with start and end dates in the past and pending payment, the membership should be in-arrears created, but it isn't and instead it follow the rest of the defined membership status rules.
For example and assuming today date is 24/1/2020, create a membership with : 
1- Start date = 1/1/2019
2- End date = keep empty
3- Membership Type = any type with 1 year period
4- Payment plan with 12 pending installments.
A membership will get created with start date = 1/1/2019, end date = 31/12/2019 and the status will be "Grace", but it should be In-arrears instead.
The issue was fixed before in BASW-65 but was interdouced again after a fix I did for MAE-171 that can be found here https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/241 .
My PR in the link above …

MAE-193: Fix in-arrears status calculation on membership creation

---

CRM/MembershipExtras/Hook/Post/MembershipPayment.php

Creating a membership with overridden status is not working and the status will be based on the membership dates and the defined status rules.
Creating a membership with overridden status will result in a membership with status that is calculated based on the membership dates and not based on the selected overridden status.
The status is selected by the user during the membership creation will be the one that the membership has.
We are forcing the extension to recalculate the membership status during the creation of the MembershipPayment entity record in order to handle "in arrears" and "not in arrears" status rules, though we are using a combination of  **MembershipStatus.calc** API end point and the membership DAO class to achieve that, and the reason is that calling the Membership API …

MAE-314: Fix membership status override during membership creation

---

info.xml

This release include the following fixes and changes : 
- BASW-622 : Hide and reserve Manage installment activity types (https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/268)
- MAE-314 : Fix membership status override during membership creation (https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/269)

MAE-327: 2.2.0 release

---

info.xml

MAE-341: Bump version number to 2.3.0

---

info.xml

Merging rc branch back to master after 2.3.0 release

MAE-341: 2.3.0 Release

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php

Reverts compucorp/uk.co.compucorp.membershipextras#278
This PR is to revere the above PR as the PR was not fully tested by QA yet.

Revert "MAE-317: Create next contribution when last contribution is not “Completed”"

---

CRM/MembershipExtras/Hook/Post/ContributionRecur.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
CRM/MembershipExtras/SettingsManager.php
api/v3/OfflineAutoRenewalJob.php
settings/PaymentPlan.setting.php
templates/CRM/MembershipExtras/Form/PaymentPlanSettings.hlp
templates/CRM/MembershipExtras/Page/CurrentPeriodTab.tpl

This PR adds additional setting field called "Update start on renewal" to Payment plan settings and update the logic for creating membership start date based on the value selected on the setting when membership is auto-renewed via schedule job. 
If the setting is checked: 
- the start date of the membership should be set to the end date +1 day
if the setting is unchecked:
- the start date of the membership remains the same
The PR also includes some other codes changes which had errors reported by PHPCS.  
1. Update start on renewal was not present. 
2. When membership is auto-renewed by schedule job, the membership start date always set to the end date +1 day.
1. Update start on renewal is added to the Payment plan settings page. 
2. When membership is auto-renewed by schedule job, the …

MAE-331: Renewal start date

---

CRM/MembershipExtras/Hook/Post/MembershipPayment.php

Completing a pending payment  for a single contribution/no payment plan membership resulted in renewing the membership twice, or in more accurate terms, extending the membership end date twice.
This issue can be produced by more than one way : 
**scenario 1**
1- Create a new single payment membership with a pending contribution (Not Payment Plan)
2- Let's say membership start date -May 7th, 2020, end Date - May 6th, 2021
3- Record a payment for the pending contribution  and use any payment method or use "Submit Credit Card payment"
4- Check the membership end date of the membership . It will be May 6th, 2022 instead of staying on May 6th, 2021.
**scenario 2** (it is a little hard to show a gif or pics for this case since the Sagepay account belongs to a client)
1- Create a webform and …

MAE-306: Fix renewing of single contribution - no payment plan membership twice after completing the payment

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/MultipleInstallmentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstallmentPlan.php
CRM/MembershipExtras/Service/MembershipEndDateCalculator.php
tests/phpunit/CRM/MembershipExtras/Service/MembershipTypeAmountProraterTest.php

This reapplies the work that was done here : https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/283
but due to the amount of code style changes it was hard to rebase it on master, so I had to cherry pick some of the commits and manually apply the others.

SPAB-1002: Implement Join Membership renewal Fixes From SPABSPRT-28

---

CRM/MembershipExtras/Hook/BuildForm/MembershipPaymentPlan.php
templates/CRM/Member/Form/PaymentPlanToggler.tpl

This PR is change wording from Installment to Instalment.
Text was Installment.
Text is not Instalment.
This PR will only affect the User Interface only and the class, variable, database schema should be changed when the work need to be done.

MAE-383: Change text on Installment to instalment on the payment plan form

---

info.xml

This PR is to bump version 3.0.0 for Membership Extras extension for ME v3 release.

MAE-385: Bump version to 3.0.0

---

info.xml

This PR Is to bump version to 3.0.1 to align with all Membeship Product Suite version 3.

MAE-385: Bump version 3.0.1

---

info.xml

Bumping version to 4.0.0 as part of Membershipextras suite version 4.0.0 release.

MAE-411: Bump version to 4.0.0

---

CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor.php

We need to allow Direct Debit extension to change payment plan first instalment receive date in such a way that:
- Takes membership start date*
- Finds the next NIRD (New instruction run date) and adds MDFNI (Min days for New instruction to First payment) 
- Finds the next payment collection run date available after the padded next instruction run date.
The payment plan's receive date is determined on a Pre hook, triggered on Contribution creation, after the membership has been created.
Added a new hook that can be implemented by other extensions to change the first instalment's receive date. This hook is triggered on the Contribution Pre hook where the recurring contribution is created. The altered receive date is then used to update the recurring contribution and first instalment's …

IO-123: Add Hook Allowing Extensions to Alter First Instalment Date

---

js/NextPeriodLineItemHandler.js

When a membership line item(Membership/Other amount) is removed from Next period tab, no activity is recorded.
https://drive.google.com/file/d/1kLdDih_HOaIubh2HVlKTtS4-00XB3ZiI/view?usp=sharing
When a membership line is created or removed, an activity is now recored.

BASW-288: Fix log activity in next period

---

info.xml

Bumping version to 4.1.0 as part of Membershipextras suite version 4.1.0 release.

MAE-457: Bump version to 4.1.0

---

CRM/MembershipExtras/Hook/CustomDispatch/CalculateContributionReceiveDate.php
CRM/MembershipExtras/Hook/CustomDispatch/PostOfflineAutoRenewal.php
CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor.php
CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentPlan.php
CRM/MembershipExtras/Page/EditContributionRecurLineItems.php
CRM/MembershipExtras/Service/InstalmentReceiveDateCalculator.php
CRM/MembershipExtras/Service/MembershipInstalmentsHandler.php
tests/phpunit/CRM/MembershipExtras/Hook/CustomDispatch/CalculateContributionReceiveDateTest.php
tests/phpunit/CRM/MembershipExtras/Hook/CustomDispatch/PostOfflineAutoRenewalTest.php
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessorTest.php

This PR is for merging master branch into membership extras version 5 work stream branch. 
Since the merging master branch into the works stream branch is not straight forward due to conflicts on following files. 
- CRM_MembershipExtras_Hook_Pre_MembershipPaymentPlanProcessor 
- CRM_MembershpExtras_Hook_Pre_MembershipPaymentPlanProcessorTest
- CRM_MembershipExtras_Service_MembershipInstalmentsHandler
- CRM_MembershipExtras_Service_InstalmentReceiveDateCalculator
The PR is also adding additional commits to fix the failing tests are on CRM_MembershpExtras_Hook_Pre_MembershipPaymentPlanProcessorTest as the tests that were merged from master branch tested against the code in the master branch which has already been updated in version 5
The reason that the merge has been used rather than …

IO-122: Merge work stream branch with master branch

---

CRM/MembershipExtras/Utils/InstalmentSchedule.php

This PR assigns the correct instalment frequency interval and unit, so the recurring contribution created with correct frequency. 
- Membership type interval was used for instalments_frequency 
- Membership type duration was used for instalments_frequency_unit
- Instalments_frequency is calculated by payment schedule.
- Instalments_frequency_unit is calculated by payment schedule and given Instalments_frequency

IO-122: Calculate instalment frequency

---

CRM/MembershipExtras/Hook/ValidateForm/MembershipPaymentPlan.php

This PR fixes when using fixed membership price set with non membership price field. 
Error thrown when using fixed membership price set with non membership price field after submitting the form.
No error thrown when using fixed membership price set with non membership price field.

MAE-490: Handle non membership price field value

---

CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
CRM/MembershipExtras/Hook/Pre/MembershipEdit.php
js/UpdateSubscriptionModifications.js
membershipextras.php
templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl
tests/phpunit/CRM/MembershipExtras/Hook/Pre/MembershipEditTest.php

Merging the fixes we did for CiviCRM 5.35 which includes : 
MAE-492: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/368
MAE-499 : https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/369

MAE-483: Merging workstream branch for CiviCRM 5.35 fixes to master branch

---

info.xml

Bump version to 4.2.0 as part of Membershipextras 5.2.0 release

MAE-512: Bump version to 4.2.0

---

.github/workflows/tests.yml
CRM/MembershipExtras/Hook/BuildForm/UpdateSubscription.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/MultiInstalmentPlanTest.php
tests/phpunit/CRM/MembershipExtras/Job/OfflineAutoRenewal/SingleInstalmentPlanTest.php

This PR is to merge master branch into Membership extras v5 work stream branch.
The reason for creating this branch instead of merging master branch into workstrem branch directly is because there is one conflict that requires to resolve.  
The conflict was from this [commit](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/b5ae3239645f0ff88294c04fffa66551e02ad604) and on membership extras v5 these codes do not exist any more and this PR resolves this issue.

MAE-525: Merge master branch to workstream branch

---

.github/workflows/tests.yml

This PR updates the test workflow docker container

MAE-610: Update Github test workflow docker container

---

Civi/Api4/PaymentScheme.php
info.xml

Adding API V4 support for `PaymentScheme` entity.

CIWEMB-248: Add API V4 support for Payment scheme entity

---

CRM/MembershipExtras/Job/OfflineAutoRenewal/PaymentSchemePlan.php

~
New hook is now  dispatched after each payment plan that is linked to payment scheme  autorenewal, the hook signature is:
```
hook_membershipextras_postPaymentSchemeRenewalAutoRenewal($paymentProcessorId, $recurContributionId, $renewalContributions)
```
where:
- $paymentProcessorId : is the payment processor id that is used to pay the payment plan
- $recurContributionId: Is the recurring contribution that got created after renewal, and that will be used for the renewed period.
- $renewalContributions: Array of contributions (instalments) that got created after the autorenewal, where each element of the array contains: `id` -> The contribution id, `total_amount` -> the contribution amount, `receive_date` -> the contribution receive date (invoice date), `currency` -> the contribution …

CIWEMB-217: Add new hook membershipextras_postPaymentSchemeRenewalAutoRenewal for payment scheme autorenwals

---

CRM/MembershipExtras/Page/EditContributionRecurLineItems.php

The "Next period" tab in the manage instalments form does not respect the the "Use latest price when auto renew membership?" setting 
and keeps showing the current period price, which will be wrong if the user add a membership line item to the current period and selects "No Payment" option or if a payment was created and the amount is  pro-rated.
Here is an example where a new membership line item is added to current period using "No Payment" option, so the amount of this line is zero:
The next period tab also shows the price of this line item to be zero even though "Use latest price when auto renew membership?"  setting is enabled:
Here is the same example above where it still shows zero in the current period tab:
but shows the correct amount in the next period tab:
Also, when switching …

CIWEMB-469: Fix next period tab line item amounts

---

info.xml

Update release info for 5.7.0 release

COMCL-347: Update release info for 5.7.0 release

---

info.xml

COMCL-458: Bump version to 6.2.0

---

CRM/MembershipExtras/Hook/PageRun/ContributionRecurViewPage.php

This pr replaces payment scheme id with admin title on recurring contribution view page.

CIWEMB-506: Show Payment Scheme Admin Title Instead Of Id

---

info.xml

COMCL-566: Bump version

---

info.xml
templates/CRM/MembershipExtras/Page/InstalmentSchedule.tpl

COMCL-907: Merge Rc Branch to Master

---

CRM/MembershipExtras/Hook/Pre/MembershipEdit.php

Prevent Membership End Date Extension After Credit Note Allocation
The membership end date is extended after credit note allocation.  
The membership end date is no longer extended after credit note allocation.  
In CiviCRM, when a payment is made to a contribution linked to an entity, the entity is updated. However, this is not the expected behavior for memberships. For more details, refer to this PR: [#485](https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/485), where we addressed this for standard payments. However, the PR did not cover credit note allocations, as these do not use the standard payment API but instead manually create the necessary payment entities.
In this pr we dont extend the membership end date if the contribution has a credit note allocated to it

CIVIMM-213: Prevent Extending Membership End Date Post Credit Note Allocation

---

templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl
templates/CRM/MembershipExtras/Page/InstalmentSchedule.tpl

This pr fixes errors that arised when smarty engine was upgraded to version 4.

COMCL-954: Add Fixes For Smarty4 Upgrade

---

info.xml
templates/CRM/Member/Form/UpdateSubscriptionModifications.tpl
templates/CRM/MembershipExtras/Page/InstalmentSchedule.tpl

This pr bumps the version to 6.8.0

COMCL-1011: Bump Version

---

info.xml

Bump version for 6.8.1 release

COMCL-1057: Bump version for 6.8.1 release

---

info.xml

Bump version for 6.8.2 release

COMCL-1099: Bump version for 6.8.2 release
